### ISSUE TITLE
can't open the application

### ISSUE THREAD

**Issue by LaurentSGL** [ticgal/gapp#10]
It is impossible for me to open the application after connection
i made several trials with other accounts : 
- my colleague with the same profile as mine : same effect
- the admin account of glpi : it's works
so it's not a network problem, neither a server configuration but user configuration

i made some trial using the api rest with postman : no problem with my account/credential to access and use the api.

so is there anything special to have on our profile ?
we've got severals entities, and a authentication based on ldap
i try with a wrong password, and i could not connect , normal
i try with the good password, and instead of having the windows with the tickets list , the app close without message

we try on two differents phone, with two different OS, and same result
GLPI version : 9.2.1

thanks for your help

**Comment by PedroTicGal** [comment]
In the next hours we are going to release a new version of GAPP with some tweaks.
Please download it and try to reproduce the issue.

Cheers!

**Comment by LaurentSGL** [comment]
:( same problem with the new version

**Comment by OscarBeiro** [comment]
Hi @LaurentSGL,
Could you confirm what is your Gapp version?

**Comment by LaurentSGL** [comment]
i use 0.9.9.5-selfservice version, of november 25th

**Comment by OscarBeiro** [comment]
Hi @LaurentSGL,

It's not possible for us to get every possible GLPI setup. If we don't manage the backend we miss a lot of information.

To solve partially this problem, since **0.9.9.6** we have enabled a Debug mode.
To activate it, please long press on the version number. This will open a dialog. If you accept, it will log all actions and send them after the crash.

This could lead us to what is breaking the app.

Regards,

**Comment by LaurentSGL** [comment]
Hi, i enable debug mode and made several trial, did you receive them ?

**Comment by OscarBeiro** [comment]
That's strange.
We haven't receive any errors from 0.9.9.6.
Could you send some screenshots and a detailed step by step?
Thanks

**Comment by LaurentSGL** [comment]
here what i can read sometimes on my phone when the app open :


java.lang.RuntimeException: Unable to start activity
ComponentInfo{gal.tic.gapp.selfservice/gal.tic.gapp.vista.MainActivity}:
java.lang.ArrayIndexOutOfBoundsException: length=1; index=-1
at
android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2984)
at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3119)
at
android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:78)
at
android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108)
at
android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68)
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1839)
at android.os.Handler.dispatchMessage(Handler.java:106)
at android.os.Looper.loop(Looper.java:201)
at android.app.ActivityThread.main(ActivityThread.java:6861)
at java.lang.reflect.Method.invoke(Native Method)
at
com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:547)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:873)
Caused by: java.lang.ArrayIndexOutOfBoundsException: length=1; index=-1
at java.util.ArrayList.get(ArrayList.java:439)
at
gal.tic.gapp.vista.MainActivity.inicializarEntitySpinner(MainActivity.java:549)
at gal.tic.gapp.vista.MainActivity.onCreate(MainActivity.java:254)
at android.app.Activity.performCreate(Activity.java:7232)
at android.app.Activity.performCreate(Activity.java:7221)
at
android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1272)
at
android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2964)
... 11 more

**Comment by PedroTicGal** [comment]
Hi Laurent.

We have received all the debug info and detected the issue. It seems that your GLPI API is not returning the information of entities, so the app is unable to point the right entity.

We recommend you to update to a newer version of GLPI (the newer the better) to see if this issue is solved, since you are using a **very old** version.

GAPP has been designed to work with GLPI 9.3+, so 9.2 version is not officially supported. Older installation may work well but bugs may raise.

**Comment by LaurentSGL** [comment]
hum..odd..
because it works with the admin account ! and with a previous version of
your app i could connect too.
we know that we do not use the last version (9.2.1) but it always a rather
big job to migrate and change the version ! i will try ..one day ! :)
thanks for your assistance
sincerely
Laurent

Le jeu. 28 nov. 2019 à 11:28, PedroTicGal <notifications@github.com> a
écrit :
