### ISSUE TITLE
[Feature] Add license files for all repositories

### ISSUE THREAD

**Issue by comradekingu** [ticgal/gapp#11]
Weblate currently lists translations as AGPLv3-only, which seems incorrect(?).
Edit: It should be AGPLv3+ is what I am thinking.

**Comment by OscarBeiro** [comment]
Weblate translation project started as a test drive, and was created fast to move away from our previous plataform which was eye-candy but a nightmare to manage.

We wanted to modify the License but don't know how. 
I have opened a ticket with support to update it.

Thanks.

**Comment by OscarBeiro** [comment]
License changed.
