### ISSUE TITLE
[Feature] Link to source/repo for Gapp

### ISSUE THREAD

**Issue by comradekingu** [ticgal/gapp#12]
Where is the actual source code for the Gapp app? Also had trouble finding the GitHub link on the website.

**Comment by OscarBeiro** [comment]
We have not released the source code. 
Maybe in the future.

This issue tracker was thought to report issues from the application itself. If you don't use Gapp you don't need to open an issue :).

Regards,

**Comment by comradekingu** [comment]
@OscarBeiro I am a translator, and in Hosted Weblate the project isn't listed as proprietary. https://hosted.weblate.org/projects/gapp/gapp-selfservice/#information
Was going to finish the translation when I noticed there was no source files as I came here to fix upstream strings.
Will remove my translation if this continues to be closed source.
You can't use AGPLv3 licensed translations in a closed source app anyway.

**Comment by OscarBeiro** [comment]
HI @comradekingu,
Sorry for the misunderstanding. We have other open source projects as you can check in our public repo. Gapp Essentials, a Gapp companion plugin is one of them: https://github.com/ticgal/gappessentials

I completely understand your position, and have removed your translation from Weblate Gapp project.
![image](https://user-images.githubusercontent.com/18396050/72969285-73456200-3dc5-11ea-85d4-e489b0330a4b.png)


Regards,

**Comment by comradekingu** [comment]
@OscarBeiro You also can't relicense someone else's work into Creative Commons Attribution 4.0 International.
