### ISSUE TITLE
[Feature] Ticket Validation

### ISSUE THREAD

**Issue by claudiatobarrodriguez** [ticgal/gapp#14]
Install gapp essentials on my mobile device, everything is correct but I do not see the approval requests or validations of glpi only allows to approve or reject resolved tickets are different contexts.
Could we have that option?
attached image for reference
excellent work!
![imagen](https://user-images.githubusercontent.com/44502507/73862672-e65ec780-480c-11ea-93fc-4d88ea86393a.png)

not displayed by the app:

![imagen](https://user-images.githubusercontent.com/44502507/73862949-4bb2b880-480d-11ea-9137-573525734c65.png)

thanks.

:)

**Comment by OscarBeiro** [comment]
Hola Claudia :)

Solutions validation is the one showing currently in Gapp.
This other ticket validation feature is not yet developed. If you want to sponsor it, please contact us,

Saludos,

**Comment by OscarBeiro** [comment]
By the way, you could help us very much rating the app:
https://play.google.com/store/apps/details?id=gal.tic.gapp.selfservice

Thanks

**Comment by PedroTicGal** [comment]
Hi @claudiatobarrodriguez ,

In the latest release of Gapp (Gapp 2.2) now it is possible to see ticket validation within the app.

I am attaching some screenshots about it.

Cheers!

![Screenshot_20220919-125707](https://user-images.githubusercontent.com/48908942/191003261-73294015-1fc9-41f2-8364-ebc047a72a7c.jpg)
![Screenshot_20220915-091945](https://user-images.githubusercontent.com/48908942/191003278-94ac14da-d57c-4e98-ba36-c0578e41daf8.jpg)
![Screenshot_20220919-125659](https://user-images.githubusercontent.com/48908942/191003295-13ff7635-d0f6-45b0-aacb-a94ec71fbda1.jpg)
![Screenshot_20220915-091922](https://user-images.githubusercontent.com/48908942/191003330-8fcf8337-3deb-4d6a-bb99-4a913939557c.jpg)
