### ISSUE TITLE
[Feature] search ticket

### ISSUE THREAD

**Issue by nykroy** [ticgal/gapp#16]
Hi. Do you think it is a good idea to have a search box to put the id and we can search the ticket?

**Comment by OscarBeiro** [comment]
Hi @nykroy,

First of all, thank you for using Gapp and taking time to give us feedback about it!

This is absolutely on our To do list. If you want it soon on Gapp, please consider sponsoring it.

We'd like to thank you again for giving us feedback and we'd be very grateful if you could rate Gapp on Google Play to help us spread the word!

Cheers!

**Comment by OscarBeiro** [comment]
Hi @nykroy ,

This feature was added a while ago. Sorry about the belated update.
![image](https://user-images.githubusercontent.com/18396050/106623129-94ae6180-6574-11eb-9c4d-569c9d020dfa.png)
