### ISSUE TITLE
[Feature] Option to Choose What Language Use

### ISSUE THREAD

**Issue by ThigSchuch** [ticgal/gapp#18]
**"Problem"**
Some of us use the phone in another language (who knows why), but it happens and sometimes we want to use certain apps in our native language.
So we have to enter in our phone's config, and change the all system language back to our native.

**Solution**
A option in menu to we be able to choose what language we want to use, as happens in Telegram, for example.

See the screenshots:
![image](https://user-images.githubusercontent.com/20743110/75254994-00fadf80-57c0-11ea-9628-964902102382.png)

![image](https://user-images.githubusercontent.com/20743110/75254997-048e6680-57c0-11ea-910b-343c403bd8ff.png)

**Comment by OscarBeiro** [comment]
We think languages autoconfig is the easiest way for end-users, but "we feel your pain" when testing other languages. We need to change the system language to check it.

So, great idea! We will add it to the roadmap.

Obrigado @ThigSchuch,

**Comment by OscarBeiro** [comment]
Hi @ThigSchuch,

We have finished your requested feature. It will be released soon.

![gapp-self-service 1 1 0-select-language](https://user-images.githubusercontent.com/18396050/76886346-f55f7d80-6880-11ea-803d-2c6e8bb22c01.jpg)

Obrigado,
