### ISSUE TITLE
Error in app

### ISSUE THREAD

**Issue by RageshR007** [ticgal/gapp#2]
Hi...I had successfully configured API and installed the app on android mobile ..Able to log in ....but no ticket is visible there ...it shows an error message as " Requested range not satisfiable :response with content range denied"....But i m able to create ticket via mobile app and its visible on web log in ...in mobile app above error shows every time and no ticket is visible.Your help and guidance would be appreciated.

**Comment by OscarBeiro** [comment]
Hi @RageshR007 Ragesh,
Please create a new ticket as a bug, adding all the necessary information, so we can try to reproduce.
Thanks

**Comment by OscarBeiro** [comment]
We continue on #3 
Thanks
