### ISSUE TITLE
Error al conectar Gapp a GLPI

### ISSUE THREAD

**Issue by djmolletones** [ticgal/gapp#20]
Al intentar conectar Gapp a mi servidor GLPI me presenta el siguiente error:

Error 007-167-->Attempt to invoke virtual method 'java.lang.Stringcom.google.gson.JsonPrimitive.getAsString()' on a null object reference

![image](https://user-images.githubusercontent.com/17554746/81877706-cc432c80-9553-11ea-95c2-460645ac4ad9.png)

Ya he configurado la conexión en la aplicación, Protocolo: http y la IP de mi servidor.

En mi GLPI he configurado el API, sin Token.

**Smartphone (please complete the following information):**
 - Device: Xiaomi Redmi 8a
 - OS: Android 9

GLPI Version: 9.4.2
Installed plugins: 
     FusionInventory
     Behaviours
     FileInjection
     Dashboard
     TimeZone
     More Reporting
     More Satisfaction

**Comment by OscarBeiro** [comment]
Hola:
Nos falta la versión de Gapp.
Saludos

**Comment by djmolletones** [comment]
Hola,

Version 1.1.1-selfservice

Saludos,

**Comment by OscarBeiro** [comment]
Hola:

Aparentemente el problema es relativo a los colores de prioridad. En Home > Setup > General > Default values

![image](https://user-images.githubusercontent.com/18396050/82025225-50e79500-9691-11ea-86da-c1bbeed2ba9d.png)

Fíjate si alguno de los **priority colors** no tiene color. No hay información sensible, así que puedes pegar un pantallazo.

En principio, vía web no es posible eliminar uno de los colores, por lo que sólo se me ocurre que alguien lo haya borrado de la base de datos.

Saludos

**Comment by djmolletones** [comment]
Hola,

No veo colores de prioridad en blanco
[image: image.png]

Efectivamente, la prioridad 2, en negro, la he ajustado y he ingresado sin
inconvenientes.

Muchas gracias por el apoyo.

**Comment by OscarBeiro** [comment]
Hola:

Si seleccionas el valor negro funciona, en tu caso me inclino porque sale negro, porque se borró de la DB.

Saludos
