### ISSUE TITLE
Duda Sobre puertos requeridos

### ISSUE THREAD

**Issue by thefamedtm** [ticgal/gapp#21]
Hola,

Me gustaría saber qué requerimientos necesitaría para poder conectar por Internet al servidor GLPI que tenemos en la oficina. Qué puertos del servidor deberían estar publicados sólo para uso de Gapp? El 80,443, etc...

Muchas gracias.

GLPI 9.4.5 + Gapp 1.1

**Comment by OscarBeiro** [comment]
Hola @thefamedtm :

Necesitas el mismo acceso que a tu GLPI. 
Si usas puertos estándar, 80 para http o 443 para https. 
Si haces algún forward o utilizas otro puerto para exponer el servidor a internet, elige ese.

Saludos
