### ISSUE TITLE
Error al momento de login - ERROR_RESOURCE_NOT_FOUND_NOR_COMMONDBTM

### ISSUE THREAD

**Issue by emaw705** [ticgal/gapp#22]
Hola, estoy probando la herramienta Gapp y estoy teniendo inconvenientes para acceder al servidor.

La configuración de la API es correcta porque mediante CURL logro conectarme y que me genere una session-token.

Para este caso, desde el mismo servidor y desde un servidor diferente ejecuto lo siguiente:

curl -X GET -H 'Content-Type: application/json' \
-H "Authorization: Basic ZXdhc2luZ2U6ITIwMTVTS..." \
'https://ruta_a_glpi/glpi/apirest.php/initSession'

y obtengo:

![image](https://user-images.githubusercontent.com/48997363/82571640-9f95a300-9b59-11ea-8f4d-91593bce09f5.png)

También tengo vacía la configuración del app_token:

![image](https://user-images.githubusercontent.com/48997363/82571759-cce25100-9b59-11ea-8102-e621fe2e46dd.png)

Sin embargo, al momento de utilizar la aplicación (V 1.1.1-selfservice) obtengo el siguiente error:

![image](https://user-images.githubusercontent.com/48997363/82572087-45491200-9b5a-11ea-9cc5-3c8279c7cc7c.png)

Busco ese mensaje de error en la documentación de Gapp y no encuentro nada.

He revisado los diferentes logs que genera GLPI y tampoco encuentro nada.

GLPI está instalado en Debian 9 mediante Apache2.

Agradecería cualquier ayuda.

Saludos.

**Comment by PedroTicGal** [comment]
Hola Emanuel, nos podrías indicar qué versión de GLPI usas?

Saludos.

**Comment by emaw705** [comment]
Hola Pedro.

La versión de GLPI es 9.4.4.

Saludos.

**Comment by OscarBeiro** [comment]
Hola Emanuel:

Parece que tu GLPI devuelve algo extraño al realizar peticiones standard a la API.
Nos inclinamos por culpar a algún plugin. Sigue estos pasos:

1. Desactiva todos los plugins

1. Intenta acceder desde la app nuevamente.

- Si es correcto el acceso, el culpable es un plugin y deberás ir activando uno a uno, y probando el acceso, hasta encontrar el que rompe la API.
- Si falla necesitaremos la información de tu 
- ¿Por casualidad tienes el plugin MyDashboard? (https://github.com/InfotelGLPI/mydashboard)

Si esto falla, necesitaremos más información de tu instalación, por favor sube este fichero aquí.
https://www.youtube.com/watch?v=9pPT3CnQhBY&t=3s

Saludos

**Comment by emaw705** [comment]
Oscar, disculpa que no te haya respondido antes.

La verdad es que hice diferentes pruebas y en todas obtengo el mismo error.

Probé la versión 9.4.4 y 9.4.5 en un entorno virtual, sin ningún plugin, y obtengo el mismo error.

Adjunto envío la información de la instalación:

[Información instalación GLPI.txt](https://github.com/ticgal/gapp/files/4724490/Informacion.instalacion.GLPI.txt)


Saludos.

**Comment by emaw705** [comment]
Oscar, quería comentarte que logré hacer andar la aplicación.

Esta vez probé con GLPI 9.4.6. Entiendo que el error mío estaba en la configuración de la dirección del servidor en GAPP.

Sin respetar lo indicado en la guía para la configuración de Gaap, agregaba al campo "Dirección del servidor" la URL + "/apirest.php".

Al sacar de la URL la cadena "/apirest.php", la misma funcionó sin ningún inconveniente.

Desde ya muchas gracias y disculpas porque el error estaba de mi parte al momento de realizar la configuración.

Saludos y buen fin de semana.

**Comment by OscarBeiro** [comment]
Hola Emanuel:

Gracias por la información. Nos ha dado una idea para intentar identificar este tipo de problemas.

Saludos
