### ISSUE TITLE
Gapp failed to connect 

### ISSUE THREAD

**Issue by daliyoucef** [ticgal/gapp#23]
<a href='https://github.com/ticgal/gapp/issues/23'>https://github.com/ticgal/gapp/issues/23</a><br><p>01:32 </p>n<p>I have always message error failed to connect to 192.168... after 5000ms ??? How to résolve this, i need help</p>n<p><img src="https://user-images.githubusercontent.com/66473763/83878299-3b1f3a00-a73c-11ea-9088-f2c7a5122808.jpg" alt="Screenshot_20200605-132926_Gapp" />nPrefer  speak in frenchnTank's</p><br>Created by daliyoucef
<blockquote>GLPI ticket number: <a href='https://xes.ticgal.com/index.php?redirect=ticket_3549' rel='nofollow'>3549</a><br/>Created with <a href='https://tic.gal'>GitSync</a> in GLPI by Óscar Beiro</blockquote>

**Comment by OscarBeiro** [comment]
Hi,
Sorry about your French-speaking request. We have not enough proficiency for that.

We will need additional information to debug your issue. Fortunately we have developed a tool to help us with it.

1. Download GAT X from: https://tic.gal/en/project/gat/
1. Uncompress and execute the jar (you will need Java 8 installed) 
1. Add your server user and password, just like you're doing in Gapp.
1. Press execute
1. This will generate a txt file.
1. Please add it to this ticket.
Merci,

**Comment by OscarBeiro** [comment]
No answer.
I close
