### ISSUE TITLE
Error en login Gapp

### ISSUE THREAD

**Issue by pacoclares** [ticgal/gapp#25]
<a href='https://github.com/ticgal/gapp/issues/25'>https://github.com/ticgal/gapp/issues/25</a><br><p>Buenos días:nEstoy probando la versión Gapp: 1.1.3-selfservice y me salta el error que os muestro:n<img src="https://user-images.githubusercontent.com/46485799/92872251-1a831200-f406-11ea-9497-d718450eb3c6.png" alt="image" />nHe configurado API:n<img src="https://user-images.githubusercontent.com/46485799/92872492-603fda80-f406-11ea-93a9-c03333586e1e.png" alt="image" />nHe configurado dirección del servidor, e intento entrar con usuarios tanto locales como de dominio y no logra acceder.n¿En API tengo que hacer algo más a nivel de ficheros o cambio de configuraciones directamente en servidor?, o ¿simplemente es configurar este apartado?.nSeguro que es cualquier tontería, pero no hay mucha info sobre la app.</p>n<p>¡Gracias por todo!</p><br>Created by pacoclares
<blockquote>GLPI ticket number: <a href='https://xes.ticgal.com/index.php?redirect=ticket_4149' rel='nofollow'>4149</a><br/>Created with <a href='https://tic.gal'>GitSync</a> in GLPI by Óscar Beiro</blockquote>

**Comment by OscarBeiro** [comment]
Hi Paco:

Information is not enough. Anyway, I think you have not followed the manual. There's a link to a GLPI API specific article: https://tic.gal/en/how-to-setup-glpi-api/

We are releasing Gapp 1.2 in a few days and some improvements are done to get more error information.

By the way, please use English when reporting here, we'll reach a broader audience this way.

Thanks for using Gapp!

**Comment by pacoclares** [comment]
Good morning Oscar:
I have simply followed all the steps, but directly, from the APP, nor does it try to log in. I have tried with GLPI local user, API created user, Synchronized Domain user. I have also tried to put server IP in configuration instead of DNS. Do you have to touch something at the server level, files ...? Any proof or idea?
Thanks for everything.

**Comment by OscarBeiro** [comment]
You are missing API Client setup in your screenshot.

Anyway you can use our debug tool, and add here the generated file.
https://tic.gal/en/project/gat/

You can remove any sensitive data, like an IP or domains, like you did in your screenshot.

This will definitively help us

**Comment by pacoclares** [comment]
Hi Oscar!:
Thanks!: This is the message:
{"serverAddress":"http://192.168.1.132","initSession":{"Error":"404:{\"Error\":\"Not Found\",\"Time_spent\":6}"}}

**Comment by OscarBeiro** [comment]
Do you need additional information? :)

Let's see:
Is your device in the same LAN, or there is any routing from your mobile phone to 192.168.1.132?
Or do you want to access a Class C IP from the Internet?

**Comment by pacoclares** [comment]
Good morning again Oscar, and thanks for everything. Yes, I am on the same internal network, I ping perfectly, and if I put in the browser: http://192.168.1.132, it appears to enter username and password, and it works perfectly with the credentials that I put in the test that you have passed me . I don't know if I have to activate or change something in 192.168.1.132 at the file level ...
![image](https://user-images.githubusercontent.com/46485799/92913508-1e755b00-f42b-11ea-9e04-a3af52f4ada9.png)

**Comment by pacoclares** [comment]
Good morning again Oscar:
I have checked the GLPI directories and I cannot find the apirest.php file in the root: In the API URL configuration, it is set as:
http://192.168.1.132/apirest.php, but in the root, this file is not there. Where should it be?

**Comment by pacoclares** [comment]
![image](https://user-images.githubusercontent.com/46485799/92915458-e1aa6380-f42c-11ea-8aa3-5f873f0ebe19.png)

**Comment by OscarBeiro** [comment]
Well, there you have.
I wouldn't trust your GLPI install if it is missing a core file :facepalm: 
You can download it from the repository. Match your installed version.
https://github.com/glpi-project/glpi/blob/9.5/bugfixes/apirest.php

**Comment by pacoclares** [comment]
Hello Oscar:
The file is already there. If I try to access, the documentation already appears:
![image](https://user-images.githubusercontent.com/46485799/92918264-8fb70d00-f42f-11ea-9594-4373f75b59f2.png)
I try again to access with the users created in that IP range, and it tells me exactly the same thing.
{"serverAddress":"http://192.168.1.132/","initSession":{"Error":"404:{\"Error\":\"Not Found\",\"Time_spent\":3}"}}
Any ideas?

**Comment by OscarBeiro** [comment]
Hi,
This is not a Gapp issue. Apparently, you have a faulty GLPI (no API).
You need to fix this. Use GLPI forums, or ask for professional support ;)
Cheers,
