### ISSUE TITLE
ERROR_RESOURCE_NOT_FOUND_NOR_COMMONDBTM

### ISSUE THREAD

**Issue by DuSantosIT** [ticgal/gapp#26]
<p><a href="https://github.com/ticgal/gapp/issues/26">https://github.com/ticgal/gapp/issues/26</a></p><p>Ao tentar acessar fazer login aparece o erro ERROR_RESOURCE_NOT_FOUND_NOR_COMMONDBTM</p><p>n</p><p>O teste foi realizado em dois ambientes. Conectando em uma rede interna (192.168.0.110) e conectando na nuvem. Em ambos o erro foi o mesmo.</p><p><br />Created by DuSantosIT</p>
<blockquote>GLPI ticket number: <a href='https://xes.ticgal.com/index.php?redirect=ticket_4255' rel='nofollow'>4255</a><br/>Created with <a href='https://tic.gal'>GitSync</a> in GLPI by Óscar Beiro</blockquote>

**Comment by xacobofg** [comment]
Olá DuSantosIT,


You didn't add any of the additional information requested, regarding your GLPI and Gapp versions.

Anyway, you can download our debug tool and add the generated file to this ticket.

https://tic.gal/en/project/gat/

**Comment by DuSantosIT** [comment]
GLPI 9.4.5
Gapp 1.2.0-selfservice

**Comment by DuSantosIT** [comment]
GAT reportou o mesmo erro.

**Comment by OscarBeiro** [comment]
Please attache GAT generated file.
Thanks

**Comment by DuSantosIT** [comment]
O GAT não gerou o arquivo.

**Comment by gitsyncuser** [comment]
<p>This is definitely a GLPI API issue. Not a Gapp one.</p><p>Anyway, if you could provide an access to your cloud instance we could try some basic debugging.</p><p>Regards,</p><blockquote>Created with <a href='https://tic.gal'>GitSync</a> in GLPI by Óscar Beiro</blockquote>
