### ISSUE TITLE
Problem of connection with GLPI 9.5.3

### ISSUE THREAD

**Issue by SwingJudge** [ticgal/gapp#28]
<p><a href="https://github.com/ticgal/gapp/issues/28">https://github.com/ticgal/gapp/issues/28</a></p><p>Hello</p><p>I have a problem since I updated my GLPI server, from version 9.5.1 to 9.5.3, unable to reconnect to the server by the GAPP application.</p><p>I have tested with a basic user type "glpi / glpi", and it works.</p><p>So I deduced that this comes from the fact that we go through a mail server to connect to GLPI.</p><p>We therefore go through our mail server which is at Google Workspace (formerly Gsuite), and so here is our connection procedure on the web version:</p><ul><li><strong>username</strong>: user's email address</li><li><strong>password</strong>: an application password generated in the Google account (different from the main password)</li><li><strong>choice of connection mode</strong>: via the Google profile which therefore allows you to go through our mail server rather than through the internal GLPI database</li></ul><p><img src="https://user-images.githubusercontent.com/45215079/100986269-42899980-354d-11eb-92c3-03dc6281535e.png" alt="image" /></p><p>When we apply the application ID and password in GAPP, we have a username or password error</p><p><img src="https://user-images.githubusercontent.com/45215079/100986929-20444b80-354e-11eb-8937-01aeb6291a39.png" alt="image" /></p><p><strong>Let me add again, with the version of GLPI in 9.5.1, the connection worked fine.</strong> We tested from smartphones running Android 10 and Android 11, and it's exactly the same problem</p><p>Can you see what it is and tell me if there is a solution?</p><p>Thank you</p><p><br />Created by SwingJudge</p>
<blockquote>GLPI ticket number: <a href='https://xes.ticgal.com/index.php?redirect=ticket_4623' rel='nofollow'>4623</a><br/>Created with <a href='https://tic.gal'>GitSync</a> in GLPI by Óscar Beiro</blockquote>

**Comment by SwingJudge** [comment]
Hi, someone have an idea?

**Comment by OscarBeiro** [comment]
Hi,

Sorry about the late reply.

We don't have enough information to debug this issue.

Could you please post your system information? Setup > General > System > Information about system installation and configuration, add the information between the code tags.

You can also use our debug tool GAT https://tic.gal/en/project/gat/ and post the generated file.

Regards,

**Comment by SwingJudge** [comment]
Hi Oscar,

Here is my system informations, thanks


[code]   
GLPI 9.5.3 ( => /var/www/vhosts/innotec-sa.com/Serveurs/SupportPROXL) Installation mode: TARBALL
--

Operating system: Linux vpscloud.innotec-sa.com 4.4.0-21-generic #37-Ubuntu SMP Mon Apr 18 18:33:37 UTC 2016 x86_64 PHP 7.2.34 fpm-fcgi (Core, PDO, PDO_ODBC, Phar, Reflection, SPL, SimpleXML, Zend OPcache, bcmath, bz2, calendar, cgi-fcgi, 	ctype, curl, date, dba, dom, enchant, exif, fileinfo, filter, ftp, gd, gettext, gmp, hash, iconv, imagick, imap, intl, ionCube 	Loader, json, ldap, libxml, mbstring, mysqli, mysqlnd, odbc, openssl, pcre, pdo_mysql, pdo_pgsql, pdo_sqlite, pgsql, posix, 	pspell, redis, session, soap, sockets, sodium, sqlite3, standard, sysvmsg, sysvsem, sysvshm, tidy, tokenizer, xml, xmlreader, 	xmlrpc, xmlwriter, xsl, zip, zlib) Setup: max_execution_time="600" memory_limit="128M" post_max_size="8M" safe_mode="" session.save_handler="files" 	upload_max_filesize="16M"  Software: Apache (Apache Server at support.proxl.fr Port 443) 	Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.88 Safari/537.36 Server Software: (Ubuntu) 	Server Version: 5.7.32-0ubuntu0.16.04.1 	Server SQL Mode:  	Parameters: jlacour@localhost/proxl_support 	Host info: Localhost via UNIX socket 	 PHP version is at least 7.2.0 - Perfect! Sessions support is available - Perfect! Allocated memory > 64 Mio - Perfect! mysqli extension is installed ctype extension is installed fileinfo extension is installed json extension is installed mbstring extension is installed iconv extension is installed zlib extension is installed curl extension is installed gd extension is installed simplexml extension is installed intl extension is installed ldap extension is installed apcu extension is not present Zend OPcache extension is installed xmlrpc extension is installed CAS extension is not present exif extension is installed zip extension is installed bz2 extension is installed sodium extension is installed Database version seems correct (5.7.32) - Perfect! Access to timezone database (mysql) is not allowed. The log file has been created successfully. Write access to /var/www/vhosts/innotec-sa.com/Serveurs/SupportPROXL/config has been validated. Write access to /var/www/vhosts/innotec-sa.com/Serveurs/SupportPROXL/files has been validated. Write access to /var/www/vhosts/innotec-sa.com/Serveurs/SupportPROXL/files/_dumps has been validated. Write access to /var/www/vhosts/innotec-sa.com/Serveurs/SupportPROXL/files/_sessions has been validated. Write access to /var/www/vhosts/innotec-sa.com/Serveurs/SupportPROXL/files/_cron has been validated. Write access to /var/www/vhosts/innotec-sa.com/Serveurs/SupportPROXL/files/_graphs has been validated. Write access to /var/www/vhosts/innotec-sa.com/Serveurs/SupportPROXL/files/_lock has been validated. Write access to /var/www/vhosts/innotec-sa.com/Serveurs/SupportPROXL/files/_plugins has been validated. Write access to /var/www/vhosts/innotec-sa.com/Serveurs/SupportPROXL/files/_tmp has been validated. Write access to /var/www/vhosts/innotec-sa.com/Serveurs/SupportPROXL/files/_cache has been validated. Write access to /var/www/vhosts/innotec-sa.com/Serveurs/SupportPROXL/files/_rss has been validated. Write access to /var/www/vhosts/innotec-sa.com/Serveurs/SupportPROXL/files/_uploads has been validated. Write access to /var/www/vhosts/innotec-sa.com/Serveurs/SupportPROXL/files/_pictures has been validated. Write access to /var/www/vhosts/innotec-sa.com/Serveurs/SupportPROXL/marketplace has been validated. Web access to files directory is protected

GLPI_ROOT: /var/www/vhosts/innotec-sa.com/Serveurs/SupportPROXL GLPI_CONFIG_DIR: /var/www/vhosts/innotec-sa.com/Serveurs/SupportPROXL/config GLPI_VAR_DIR: /var/www/vhosts/innotec-sa.com/Serveurs/SupportPROXL/files GLPI_MARKETPLACE_DIR: /var/www/vhosts/innotec-sa.com/Serveurs/SupportPROXL/marketplace GLPI_USE_CSRF_CHECK: 1 GLPI_CSRF_EXPIRES: 7200 GLPI_CSRF_MAX_TOKENS: 100 GLPI_USE_IDOR_CHECK: 1 GLPI_IDOR_EXPIRES: 7200 GLPI_TELEMETRY_URI: https://telemetry.glpi-project.org GLPI_INSTALL_MODE: TARBALL GLPI_NETWORK_MAIL: glpi@teclib.com GLPI_NETWORK_SERVICES: https://services.glpi-network.com GLPI_MARKETPLACE_PRERELEASES:  GLPI_USER_AGENT_EXTRA_COMMENTS:  GLPI_AJAX_DASHBOARD: 1 GLPI_CALDAV_IMPORT_STATE: 0 GLPI_DEMO_MODE: 0 GLPI_FORCE_EMPTY_SQL_MODE: 1 GLPI_DOC_DIR: /var/www/vhosts/innotec-sa.com/Serveurs/SupportPROXL/files GLPI_CACHE_DIR: /var/www/vhosts/innotec-sa.com/Serveurs/SupportPROXL/files/_cache GLPI_CRON_DIR: /var/www/vhosts/innotec-sa.com/Serveurs/SupportPROXL/files/_cron GLPI_DUMP_DIR: /var/www/vhosts/innotec-sa.com/Serveurs/SupportPROXL/files/_dumps GLPI_GRAPH_DIR: /var/www/vhosts/innotec-sa.com/Serveurs/SupportPROXL/files/_graphs GLPI_LOCAL_I18N_DIR: /var/www/vhosts/innotec-sa.com/Serveurs/SupportPROXL/files/_locales GLPI_LOCK_DIR: /var/www/vhosts/innotec-sa.com/Serveurs/SupportPROXL/files/_lock GLPI_LOG_DIR: /var/www/vhosts/innotec-sa.com/Serveurs/SupportPROXL/files/_log GLPI_PICTURE_DIR: /var/www/vhosts/innotec-sa.com/Serveurs/SupportPROXL/files/_pictures GLPI_PLUGIN_DOC_DIR: /var/www/vhosts/innotec-sa.com/Serveurs/SupportPROXL/files/_plugins GLPI_RSS_DIR: /var/www/vhosts/innotec-sa.com/Serveurs/SupportPROXL/files/_rss GLPI_SESSION_DIR: /var/www/vhosts/innotec-sa.com/Serveurs/SupportPROXL/files/_sessions GLPI_TMP_DIR: /var/www/vhosts/innotec-sa.com/Serveurs/SupportPROXL/files/_tmp GLPI_UPLOAD_DIR: /var/www/vhosts/innotec-sa.com/Serveurs/SupportPROXL/files/_uploads GLPI_NETWORK_REGISTRATION_API_URL: https://services.glpi-network.com/api/registration/ GLPI_MARKETPLACE_PLUGINS_API_URI: https://services.glpi-network.com/api/glpi-plugins/ GLPI_I18N_DIR: /var/www/vhosts/innotec-sa.com/Serveurs/SupportPROXL/locales GLPI_VERSION: 9.5.3 GLPI_SCHEMA_VERSION: 9.5.3 GLPI_MIN_PHP: 7.2.0 GLPI_YEAR: 2020

htmlawed/htmlawed version 1.2.5 in (/var/www/vhosts/innotec-sa.com/Serveurs/SupportPROXL/vendor/htmlawed/htmlawed) phpmailer/phpmailer version 6.1.6 in (/var/www/vhosts/innotec-sa.com/Serveurs/SupportPROXL/vendor/phpmailer/phpmailer/src) simplepie/simplepie version 1.5.6 in (/var/www/vhosts/innotec-sa.com/Serveurs/SupportPROXL/vendor/simplepie/simplepie/library) tecnickcom/tcpdf version 6.3.5 in (/var/www/vhosts/innotec-sa.com/Serveurs/SupportPROXL/vendor/tecnickcom/tcpdf) michelf/php-markdown in (/var/www/vhosts/innotec-sa.com/Serveurs/SupportPROXL/vendor/michelf/php-markdown/Michelf) true/punycode in (/var/www/vhosts/innotec-sa.com/Serveurs/SupportPROXL/vendor/true/punycode/src) iamcal/lib_autolink in (/var/www/vhosts/innotec-sa.com/Serveurs/SupportPROXL/vendor/iamcal/lib_autolink) sabre/dav in (/var/www/vhosts/innotec-sa.com/Serveurs/SupportPROXL/vendor/sabre/dav/lib/DAV) sabre/http in (/var/www/vhosts/innotec-sa.com/Serveurs/SupportPROXL/vendor/sabre/http/lib) sabre/uri in (/var/www/vhosts/innotec-sa.com/Serveurs/SupportPROXL/vendor/sabre/uri/lib) sabre/vobject in (/var/www/vhosts/innotec-sa.com/Serveurs/SupportPROXL/vendor/sabre/vobject/lib) laminas/laminas-cache in (/var/www/vhosts/innotec-sa.com/Serveurs/SupportPROXL/vendor/laminas/laminas-cache/src) laminas/laminas-i18n in (/var/www/vhosts/innotec-sa.com/Serveurs/SupportPROXL/vendor/laminas/laminas-i18n/src) laminas/laminas-serializer in (/var/www/vhosts/innotec-sa.com/Serveurs/SupportPROXL/vendor/laminas/laminas-serializer/src) monolog/monolog in (/var/www/vhosts/innotec-sa.com/Serveurs/SupportPROXL/vendor/monolog/monolog/src/Monolog) sebastian/diff in (/var/www/vhosts/innotec-sa.com/Serveurs/SupportPROXL/vendor/sebastian/diff/src) elvanto/litemoji in (/var/www/vhosts/innotec-sa.com/Serveurs/SupportPROXL/vendor/elvanto/litemoji/src) symfony/console in (/var/www/vhosts/innotec-sa.com/Serveurs/SupportPROXL/vendor/symfony/console) scssphp/scssphp in (/var/www/vhosts/innotec-sa.com/Serveurs/SupportPROXL/vendor/scssphp/scssphp/src) laminas/laminas-mail in (/var/www/vhosts/innotec-sa.com/Serveurs/SupportPROXL/vendor/laminas/laminas-mail/src/Protocol) laminas/laminas-mime in (/var/www/vhosts/innotec-sa.com/Serveurs/SupportPROXL/vendor/laminas/laminas-mime/src) rlanvin/php-rrule in (/var/www/vhosts/innotec-sa.com/Serveurs/SupportPROXL/vendor/rlanvin/php-rrule/src) blueimp/jquery-file-upload in (/var/www/vhosts/innotec-sa.com/Serveurs/SupportPROXL/vendor/blueimp/jquery-file-upload/server/php) ramsey/uuid in (/var/www/vhosts/innotec-sa.com/Serveurs/SupportPROXL/vendor/ramsey/uuid/src) psr/log in (/var/www/vhosts/innotec-sa.com/Serveurs/SupportPROXL/vendor/psr/log/Psr/Log) psr/simple-cache in (/var/www/vhosts/innotec-sa.com/Serveurs/SupportPROXL/vendor/psr/simple-cache/src) mexitek/phpcolors in (/var/www/vhosts/innotec-sa.com/Serveurs/SupportPROXL/vendor/mexitek/phpcolors/src/Mexitek/PHPColors) guzzlehttp/guzzle in (/var/www/vhosts/innotec-sa.com/Serveurs/SupportPROXL/vendor/guzzlehttp/guzzle/src) guzzlehttp/psr7 in (/var/www/vhosts/innotec-sa.com/Serveurs/SupportPROXL/vendor/guzzlehttp/psr7/src) wapmorgan/unified-archive in (/var/www/vhosts/innotec-sa.com/Serveurs/SupportPROXL/vendor/wapmorgan/unified-archive/src) paragonie/sodium_compat in (/var/www/vhosts/innotec-sa.com/Serveurs/SupportPROXL/vendor/paragonie/sodium_compat/src)

Not active

Way of sending emails: SMTP+TLS (julienlacour@proxl.fr@smtp-relay.sendinblue.com)

Name: 'assistance@proxl.fr' Active: Yes 	Server: '{imap.gmail.com/imap/ssl/novalidate-cert/notls}Assistance PROXL' Login: 'julienlacour@proxl.fr' Password: Yes

actualtime           Name: ActualTime                     Version: 1.4.0      State: Enabled 	fields               Name: Champs supplémentaires         Version: 1.12.0     State: Enabled 	datainjection        Name: Data Injection                 Version: 2.8.1      State: Enabled 	formcreator          Name: Form Creator                   Version: 2.10.4     State: Enabled 	gappessentials       Name: Gapp Essentials                Version: 1.2.0      State: Enabled 	gdrive               Name: GDrive                         Version: 1.3.0      State: Enabled
[/code]

**Comment by OscarBeiro** [comment]
GAT information will be needed finally,  https://tic.gal/en/project/gat/ and post the generated file.

Thanks

**Comment by SwingJudge** [comment]
I do the file with glpi user, with my credentials, i have this message 

![image](https://user-images.githubusercontent.com/45215079/102468632-12b0ba80-4052-11eb-96be-a57b32cb6989.png)



[support.proxl.fr_2020-12-17_10-21-58.txt](https://github.com/ticgal/gapp/files/5708249/support.proxl.fr_2020-12-17_10-21-58.txt)

**Comment by OscarBeiro** [comment]
Did you modify the txt in any way? Your session token is set to 000000. 

Login is OK, since API returns information about your config. 
I don't understand that GLPI behaviour.

I suggest running a GLPI test environment to test your auth method.
No data, no plugins, only test the auth.

**Comment by SwingJudge** [comment]
I don't open this file ??
i just use the user glpi with internal database .

i go to test with a test environment and i tell you.

Thanks

**Comment by SwingJudge** [comment]
Oscar, i just install a new GLPI on my webserver, i don't install any plugin, and so it's the same problem 

![image](https://user-images.githubusercontent.com/45215079/102480763-0b44dd80-4061-11eb-9168-6ccb46344dc2.png)


so i do a GAT file with user "glpi"
[glpi.proxl.fr_2020-12-17_12-09-36.txt](https://github.com/ticgal/gapp/files/5708904/glpi.proxl.fr_2020-12-17_12-09-36.txt)

and system informations


[code]   GLPI 9.5.3 ( => /var/www/vhosts/innotec-sa.com/Serveurs/glpitest) Installation mode: TARBALL
--

Operating system: Linux vpscloud.innotec-sa.com 4.4.0-21-generic #37-Ubuntu SMP Mon Apr 18 18:33:37 UTC 2016 x86_64 PHP 7.2.34 fpm-fcgi (Core, PDO, PDO_ODBC, Phar, Reflection, SPL, SimpleXML, Zend OPcache, bcmath, bz2, calendar, cgi-fcgi, 	ctype, curl, date, dba, dom, enchant, exif, fileinfo, filter, ftp, gd, gettext, gmp, hash, iconv, imagick, imap, intl, ionCube 	Loader, json, ldap, libxml, mbstring, mysqli, mysqlnd, odbc, openssl, pcre, pdo_mysql, pdo_pgsql, pdo_sqlite, pgsql, posix, 	pspell, redis, session, soap, sockets, sodium, sqlite3, standard, sysvmsg, sysvsem, sysvshm, tidy, tokenizer, xml, xmlreader, 	xmlrpc, xmlwriter, xsl, zip, zlib) Setup: max_execution_time="30" memory_limit="128M" post_max_size="8M" safe_mode="" session.save_handler="files" 	upload_max_filesize="2M"  Software: Apache (Apache Server at glpi.proxl.fr Port 443) 	Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.88 Safari/537.36 Server Software: (Ubuntu) 	Server Version: 5.7.32-0ubuntu0.16.04.1 	Server SQL Mode:  	Parameters: SwingJudge@localhost/glpi_test 	Host info: Localhost via UNIX socket 	 PHP version is at least 7.2.0 - Perfect! Sessions support is available - Perfect! Allocated memory > 64 Mio - Perfect! mysqli extension is installed ctype extension is installed fileinfo extension is installed json extension is installed mbstring extension is installed iconv extension is installed zlib extension is installed curl extension is installed gd extension is installed simplexml extension is installed intl extension is installed ldap extension is installed apcu extension is not present Zend OPcache extension is installed xmlrpc extension is installed CAS extension is not present exif extension is installed zip extension is installed bz2 extension is installed sodium extension is installed Database version seems correct (5.7.32) - Perfect! Access to timezone database (mysql) is not allowed. The log file has been created successfully. Write access to /var/www/vhosts/innotec-sa.com/Serveurs/glpitest/config has been validated. Write access to /var/www/vhosts/innotec-sa.com/Serveurs/glpitest/files has been validated. Write access to /var/www/vhosts/innotec-sa.com/Serveurs/glpitest/files/_dumps has been validated. Write access to /var/www/vhosts/innotec-sa.com/Serveurs/glpitest/files/_sessions has been validated. Write access to /var/www/vhosts/innotec-sa.com/Serveurs/glpitest/files/_cron has been validated. Write access to /var/www/vhosts/innotec-sa.com/Serveurs/glpitest/files/_graphs has been validated. Write access to /var/www/vhosts/innotec-sa.com/Serveurs/glpitest/files/_lock has been validated. Write access to /var/www/vhosts/innotec-sa.com/Serveurs/glpitest/files/_plugins has been validated. Write access to /var/www/vhosts/innotec-sa.com/Serveurs/glpitest/files/_tmp has been validated. Write access to /var/www/vhosts/innotec-sa.com/Serveurs/glpitest/files/_cache has been validated. Write access to /var/www/vhosts/innotec-sa.com/Serveurs/glpitest/files/_rss has been validated. Write access to /var/www/vhosts/innotec-sa.com/Serveurs/glpitest/files/_uploads has been validated. Write access to /var/www/vhosts/innotec-sa.com/Serveurs/glpitest/files/_pictures has been validated. Write access to /var/www/vhosts/innotec-sa.com/Serveurs/glpitest/marketplace has been validated. Web access to files directory is protected

GLPI_ROOT: /var/www/vhosts/innotec-sa.com/Serveurs/glpitest GLPI_CONFIG_DIR: /var/www/vhosts/innotec-sa.com/Serveurs/glpitest/config GLPI_VAR_DIR: /var/www/vhosts/innotec-sa.com/Serveurs/glpitest/files GLPI_MARKETPLACE_DIR: /var/www/vhosts/innotec-sa.com/Serveurs/glpitest/marketplace GLPI_USE_CSRF_CHECK: 1 GLPI_CSRF_EXPIRES: 7200 GLPI_CSRF_MAX_TOKENS: 100 GLPI_USE_IDOR_CHECK: 1 GLPI_IDOR_EXPIRES: 7200 GLPI_TELEMETRY_URI: https://telemetry.glpi-project.org GLPI_INSTALL_MODE: TARBALL GLPI_NETWORK_MAIL: glpi@teclib.com GLPI_NETWORK_SERVICES: https://services.glpi-network.com GLPI_MARKETPLACE_PRERELEASES:  GLPI_USER_AGENT_EXTRA_COMMENTS:  GLPI_AJAX_DASHBOARD: 1 GLPI_CALDAV_IMPORT_STATE: 0 GLPI_DEMO_MODE: 0 GLPI_FORCE_EMPTY_SQL_MODE: 1 GLPI_DOC_DIR: /var/www/vhosts/innotec-sa.com/Serveurs/glpitest/files GLPI_CACHE_DIR: /var/www/vhosts/innotec-sa.com/Serveurs/glpitest/files/_cache GLPI_CRON_DIR: /var/www/vhosts/innotec-sa.com/Serveurs/glpitest/files/_cron GLPI_DUMP_DIR: /var/www/vhosts/innotec-sa.com/Serveurs/glpitest/files/_dumps GLPI_GRAPH_DIR: /var/www/vhosts/innotec-sa.com/Serveurs/glpitest/files/_graphs GLPI_LOCAL_I18N_DIR: /var/www/vhosts/innotec-sa.com/Serveurs/glpitest/files/_locales GLPI_LOCK_DIR: /var/www/vhosts/innotec-sa.com/Serveurs/glpitest/files/_lock GLPI_LOG_DIR: /var/www/vhosts/innotec-sa.com/Serveurs/glpitest/files/_log GLPI_PICTURE_DIR: /var/www/vhosts/innotec-sa.com/Serveurs/glpitest/files/_pictures GLPI_PLUGIN_DOC_DIR: /var/www/vhosts/innotec-sa.com/Serveurs/glpitest/files/_plugins GLPI_RSS_DIR: /var/www/vhosts/innotec-sa.com/Serveurs/glpitest/files/_rss GLPI_SESSION_DIR: /var/www/vhosts/innotec-sa.com/Serveurs/glpitest/files/_sessions GLPI_TMP_DIR: /var/www/vhosts/innotec-sa.com/Serveurs/glpitest/files/_tmp GLPI_UPLOAD_DIR: /var/www/vhosts/innotec-sa.com/Serveurs/glpitest/files/_uploads GLPI_NETWORK_REGISTRATION_API_URL: https://services.glpi-network.com/api/registration/ GLPI_MARKETPLACE_PLUGINS_API_URI: https://services.glpi-network.com/api/glpi-plugins/ GLPI_I18N_DIR: /var/www/vhosts/innotec-sa.com/Serveurs/glpitest/locales GLPI_VERSION: 9.5.3 GLPI_SCHEMA_VERSION: 9.5.3 GLPI_MIN_PHP: 7.2.0 GLPI_YEAR: 2020

htmlawed/htmlawed version 1.2.5 in (/var/www/vhosts/innotec-sa.com/Serveurs/glpitest/vendor/htmlawed/htmlawed) phpmailer/phpmailer version 6.1.6 in (/var/www/vhosts/innotec-sa.com/Serveurs/glpitest/vendor/phpmailer/phpmailer/src) simplepie/simplepie version 1.5.6 in (/var/www/vhosts/innotec-sa.com/Serveurs/glpitest/vendor/simplepie/simplepie/library) tecnickcom/tcpdf version 6.3.5 in (/var/www/vhosts/innotec-sa.com/Serveurs/glpitest/vendor/tecnickcom/tcpdf) michelf/php-markdown in (/var/www/vhosts/innotec-sa.com/Serveurs/glpitest/vendor/michelf/php-markdown/Michelf) true/punycode in (/var/www/vhosts/innotec-sa.com/Serveurs/glpitest/vendor/true/punycode/src) iamcal/lib_autolink in (/var/www/vhosts/innotec-sa.com/Serveurs/glpitest/vendor/iamcal/lib_autolink) sabre/dav in (/var/www/vhosts/innotec-sa.com/Serveurs/glpitest/vendor/sabre/dav/lib/DAV) sabre/http in (/var/www/vhosts/innotec-sa.com/Serveurs/glpitest/vendor/sabre/http/lib) sabre/uri in (/var/www/vhosts/innotec-sa.com/Serveurs/glpitest/vendor/sabre/uri/lib) sabre/vobject in (/var/www/vhosts/innotec-sa.com/Serveurs/glpitest/vendor/sabre/vobject/lib) laminas/laminas-cache in (/var/www/vhosts/innotec-sa.com/Serveurs/glpitest/vendor/laminas/laminas-cache/src) laminas/laminas-i18n in (/var/www/vhosts/innotec-sa.com/Serveurs/glpitest/vendor/laminas/laminas-i18n/src) laminas/laminas-serializer in (/var/www/vhosts/innotec-sa.com/Serveurs/glpitest/vendor/laminas/laminas-serializer/src) monolog/monolog in (/var/www/vhosts/innotec-sa.com/Serveurs/glpitest/vendor/monolog/monolog/src/Monolog) sebastian/diff in (/var/www/vhosts/innotec-sa.com/Serveurs/glpitest/vendor/sebastian/diff/src) elvanto/litemoji in (/var/www/vhosts/innotec-sa.com/Serveurs/glpitest/vendor/elvanto/litemoji/src) symfony/console in (/var/www/vhosts/innotec-sa.com/Serveurs/glpitest/vendor/symfony/console) scssphp/scssphp in (/var/www/vhosts/innotec-sa.com/Serveurs/glpitest/vendor/scssphp/scssphp/src) laminas/laminas-mail in (/var/www/vhosts/innotec-sa.com/Serveurs/glpitest/vendor/laminas/laminas-mail/src/Protocol) laminas/laminas-mime in (/var/www/vhosts/innotec-sa.com/Serveurs/glpitest/vendor/laminas/laminas-mime/src) rlanvin/php-rrule in (/var/www/vhosts/innotec-sa.com/Serveurs/glpitest/vendor/rlanvin/php-rrule/src) blueimp/jquery-file-upload in (/var/www/vhosts/innotec-sa.com/Serveurs/glpitest/vendor/blueimp/jquery-file-upload/server/php) ramsey/uuid in (/var/www/vhosts/innotec-sa.com/Serveurs/glpitest/vendor/ramsey/uuid/src) psr/log in (/var/www/vhosts/innotec-sa.com/Serveurs/glpitest/vendor/psr/log/Psr/Log) psr/simple-cache in (/var/www/vhosts/innotec-sa.com/Serveurs/glpitest/vendor/psr/simple-cache/src) mexitek/phpcolors in (/var/www/vhosts/innotec-sa.com/Serveurs/glpitest/vendor/mexitek/phpcolors/src/Mexitek/PHPColors) guzzlehttp/guzzle in (/var/www/vhosts/innotec-sa.com/Serveurs/glpitest/vendor/guzzlehttp/guzzle/src) guzzlehttp/psr7 in (/var/www/vhosts/innotec-sa.com/Serveurs/glpitest/vendor/guzzlehttp/psr7/src) wapmorgan/unified-archive in (/var/www/vhosts/innotec-sa.com/Serveurs/glpitest/vendor/wapmorgan/unified-archive/src) paragonie/sodium_compat in (/var/www/vhosts/innotec-sa.com/Serveurs/glpitest/vendor/paragonie/sodium_compat/src)

Not active

Way of sending emails: PHP

 

gappessentials       Name: Gapp Essentials                Version: 1.2.0      State: Not installed
[/code]

**Comment by OscarBeiro** [comment]
We are unable to replicate. We have tested on 9.5.3 and works well.
Could you please provide a test user/pass?

**Comment by gitsyncuser** [comment]
<p>Testing</p><blockquote>Created with <a href='https://tic.gal'>GitSync</a> in GLPI by Óscar Beiro</blockquote>

**Comment by SwingJudge** [comment]
can i send you in private message the testing user/pass?

**Comment by SwingJudge** [comment]
i send you on mail 
thanks

**Comment by SwingJudge** [comment]
Hi Oscar,

i don't understand your messages from your GLPI support, i sended you our login for our glpi test, i see you create a ticket, but i still cannot connect to this with this login, by the web site, yes, but not by the app.

**Comment by OscarBeiro** [comment]
Hi,
I have already answer on our ticket.
We have investigated the issue, and the GLPI API apparently is not considering IMAP authentication. Because of this, Gapp is unable to authenticate.

You could open an issue at the GLPI project, to report it.
Regards,
