### ISSUE TITLE
 doesn't login

### ISSUE THREAD

**Issue by DanielLLQ** [ticgal/gapp#29]
<p><a href="https://github.com/ticgal/gapp/issues/29">https://github.com/ticgal/gapp/issues/29</a></p><p>GLPI 9.5.3 Gapp1.2.0 after entering the login and password, asks them again and does not allow them to be entered, then an endless connection occurs. there is nothing in the server logs. <img src="https://user-images.githubusercontent.com/77854150/105529590-cb80ae00-5d10-11eb-85fd-a7a0d21df78e.png" alt="Screenshot_20210122-235606" /></p><p><br />Creado por DanielLLQ</p>
<blockquote>Numero de la peticion de GLPI: <a href='https://xes.ticgal.com/index.php?redirect=ticket_4886' rel='nofollow'>4886</a><br/>Creado por <a href='https://tic.gal'>GitSync</a> en GLPI por Óscar Beiro</blockquote>

**Comment by PedroTicGal** [comment]
Hi @DanielLLQ,

First of all, thank you for using Gapp and providing us feedback :)

When you login in Gapp within your GLPI enviroment, Gapp expects a json with the token provided by your server.
If, instead, your server gives in return a html web page, Gapp shows it to you to help you out find the issue.

Usually this kind of issues are refered to firewall, proxies, and all sort of blockers.
This messages means that your web server is not configured correctly.

**Comment by DanielLLQ** [comment]
Hello. Thanks for answering.
Where can I get the json file for glpi? and how can I add a web server to the configs? 25.01.2021, 18:34, "Pedro Muñoz" <notifications@github.com>: Hi @DanielLLQ,First of all, thank you for using Gapp and providing us feedback :)When you login in Gapp within your GLPI enviroment, Gapp expects a json with the token provided by your server.If, instead, your server gives in return a html web page, Gapp shows it to you to help you out find the issue.Ussually this kind of issues are refered to firewall, proxies, and all sort of blockers.This messages means that your web server is not configured correctly.—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or unsubscribe.  -- С уважением,Литвиц Даниель Системный администраторООО"Лаборатория ИТ-Решений"

**Comment by OscarBeiro** [comment]
Hi @DanielLLQ,

We have some miscommunication here.

A JSON file is what GLPI returns when making a request to the API. In your environment, no JSON file is been returned, but an HTML file with the Login. This means you have an issue with your webserver configuration.

This is not a Gapp or GLPI issue, but a Webserver one. Ask your Sysadmin to fix it for you, or you can professional support to fix it.  

Cheers,
