### ISSUE TITLE
Bug Gapp

### ISSUE THREAD

**Issue by RageshR007** [ticgal/gapp#3]
**Describe the bug**
Hi...I had successfully configured API and installed the app on android mobile ..Able to log in ....but no ticket is visible there ...it shows an error message as " Requested range not satisfiable :response with content range denied"....But i m able to create ticket via mobile app and its visible on web log in ...in mobile app above error shows every time and no ticket is visible.Your help and guidance would be appreciated.

**To Reproduce**
1.Install app
2.Configure server URL on app
3.Log in 
4.Once loged in it shows error " Requested range not satisfiable :response with content range denied"

**Expected behavior**
shows an error message as " Requested range not satisfiable :response with content range denied" when ever try to check tickets..No tickets listing.

**Screenshots**
![image](https://user-images.githubusercontent.com/56621454/66906068-9c1ac600-f024-11e9-924d-0af3955a2ef4.png)

![image](https://user-images.githubusercontent.com/56621454/66906114-b18ff000-f024-11e9-9807-dbc49a49e3f8.png)

**Smartphone (please complete the following information):**
 - Device: [e.g. Huawei Honer 9A]
 - OS: Android 8.0.0

**Your GLPI server**
 - GLPI Version: 9.3.3
 - Installed plugins:
Additionnal fields	1.8.2	
Dashboard	0.9.6	
Diagrams	2.0.15
Forms	2.7.0
GLPI Modifications  1.2.6	
Mail Analyzer	1.3.8
More Reporting	1.5.3	
OCS Inventory NG	
Print to pdf	1.4.0
Shell Commands 2.2.2

**Additional context**

**Comment by OscarBeiro** [comment]
Hi Ragesh,
We have been simulating possible problems, and cannot reproduce.
- If the number of ticket were to big, you would get a timeout.

Your error is a **416 Requested Range Not Satisfiable**. Are you using Apache? Error logs could bring more light to this issue. Please post the Apache error.
Regards,

**Comment by RageshR007** [comment]
Pls see the Apache web server error log


137.97.125.255 - ragesh [17/Oct/2019:13:00:18 +0530] "GET /octa-it/apirest.php/initSession/ HTTP/1.1" 200 46 "-" "Dalvik/2.1.0 (Linux; U; Android 8.0.0; AUM-AL20 Build/HONORAUM-AL20)"
137.97.125.255 - - [17/Oct/2019:13:00:19 +0530] "GET /octa-it/plugins/gappessentials/apirest.php/pluginList HTTP/1.1" 404 251 "-" "Dalvik/2.1.0 (Linux; U; Android 8.0.0; AUM-AL20 Build/HONORAUM-AL20)"
137.97.125.255 - - [17/Oct/2019:13:00:19 +0530] "GET /octa-it/apirest.php/getFullSession HTTP/1.1" 200 8524 "-" "Dalvik/2.1.0 (Linux; U; Android 8.0.0; AUM-AL20 Build/HONORAUM-AL20)"
137.97.125.255 - - [17/Oct/2019:13:00:19 +0530] "GET /octa-it/apirest.php/getGlpiConfig HTTP/1.1" 200 19972 "-" "Dalvik/2.1.0 (Linux; U; Android 8.0.0; AUM-AL20 Build/HONORAUM-AL20)"
137.97.125.255 - - [17/Oct/2019:13:00:19 +0530] "GET /octa-it/plugins/gappessentials/apirest.php/basicInfo HTTP/1.1" 404 250 "-" "Dalvik/2.1.0 (Linux; U; Android 8.0.0; AUM-AL20 Build/HONORAUM-AL20)"
137.97.125.255 - - [17/Oct/2019:13:00:19 +0530] "POST /octa-it/apirest.php/getMyEntities HTTP/1.1" 200 537 "-" "Dalvik/2.1.0 (Linux; U; Android 8.0.0; AUM-AL20 Build/HONORAUM-AL20)"
137.97.125.255 - - [17/Oct/2019:13:00:20 +0530] "POST /octa-it/apirest.php/getMyProfiles HTTP/1.1" 200 373 "-" "Dalvik/2.1.0 (Linux; U; Android 8.0.0; AUM-AL20 Build/HONORAUM-AL20)"
137.97.125.255 - - [17/Oct/2019:13:00:20 +0530] "GET /octa-it/apirest.php/search/Ticket?uid_cols=true&is_deleted=0&criteria[0][link]=AND&criteria[0][field]=12&criteria[0][searchtype]=equals&criteria[0][value]=5&criteria[1][link]=AND&criteria[1][field]=4&criteria[1][searchtype]=equals&criteria[1][value]=18&sort=19&order=DESC&range=0-200 HTTP/1.1" 200 76 "-" "Dalvik/2.1.0 (Linux; U; Android 8.0.0; AUM-AL20 Build/HONORAUM-AL20)"
137.97.125.255 - - [17/Oct/2019:13:00:20 +0530] "GET /octa-it/apirest.php/search/Ticket?uid_cols=true&is_deleted=0&forcedisplay[0]=21&forcedisplay[1]=19&forcedisplay[2]=12&forcedisplay[3]=3&forcedisplay[4]=80&forcedisplay[5]=15&forcedisplay[6]=14&criteria[0][link]=AND&criteria[0][field]=12&criteria[0][searchtype]=equals&criteria[0][value]=1&criteria[1][link]=AND&criteria[1][field]=5&criteria[1][searchtype]=equals&criteria[1][value]=18&criteria[2][link]=OR&criteria[2][field]=12&criteria[2][searchtype]=equals&criteria[2][value]=2&criteria[3][link]=AND&criteria[3][field]=5&criteria[3][searchtype]=equals&criteria[3][value]=18&criteria[4][link]=OR&criteria[4][field]=12&criteria[4][searchtype]=equals&criteria[4][value]=3&criteria[5][link]=AND&criteria[5][field]=5&criteria[5][searchtype]=equals&criteria[5][value]=18&criteria[6][link]=OR&criteria[6][field]=12&criteria[6][searchtype]=equals&criteria[6][value]=4&criteria[7][link]=AND&criteria[7][field]=5&criteria[7][searchtype]=equals&criteria[7][value]=18&sort=19&order=DESC&range=0-200 HTTP/1.1" 200 745 "-" "Dalvik/2.1.0 (Linux; U; Android 8.0.0; AUM-AL20 Build/HONORAUM-AL20)"

**Comment by RageshR007** [comment]
![Screenshot_20191017-170215](https://user-images.githubusercontent.com/56621454/67005391-1e2bed00-f100-11e9-92ee-eb42ae2019b1.jpg)

In order to reproduce the issue..You can test it by adding given url on the screenshot  to your phone app and log in with below cedentials
ID- glpitest

**Comment by OscarBeiro** [comment]
I've removed password. Will test it and give you some feedback.

**Comment by OscarBeiro** [comment]
Hi,

This is an specific problem to your setup. Your watchguard is blocking some requests. 

![1589b1f5-f02f-42e1-852a-090e46eaabfc](https://user-images.githubusercontent.com/18396050/67008220-5aa01e80-f0e9-11e9-81e1-ec1c787f5c44.jpeg)

https://www.watchguard.com/help/docs/help-center/en-US/Content/en-US/Fireware/proxies/http/http_proxy_deny_msg_c.html

We'll use this ticket as a reminder that user setups is a variable we cannot address.

Cheers,

**Comment by RageshR007** [comment]
Thanks to shed light on this issue....Our IT security team been resolved the issue...Once again thanks and your app working awesome.
