### ISSUE TITLE
List All tickets except those assigned to another users of the group

### ISSUE THREAD

**Issue by dxdemetriou** [ticgal/gapp#31]
<p><a href="https://github.com/ticgal/gapp/issues/31">https://github.com/ticgal/gapp/issues/31</a></p><p>It will be more helpfull to easily see "all tickets" except those that are "currently in process by a person of the group". For example if there is a group of 20 people, each person is self-assigned the ticket that will be handled by him/her, so every other people of the group knows that this ticket is currently in-progress (like by a telephone call). Another example is the filtering of all tickets that are not assigned to any person of the group.</p><p>Some solutions could be:</p><ul><li>Showing the assigned user in the "All Tickets"</li><li>Creating a new category, like "Assigned tickets to others"</li></ul><p><br />Creado por dxdemetriou</p>
<blockquote>GLPI ticket number: <a href='https://xes.ticgal.com/index.php?redirect=ticket_5990' rel='nofollow'>5990</a><br/>Created with <a href='https://tic.gal'>GitSync</a> in GLPI by Óscar Beiro</blockquote>

**Comment by OscarBeiro** [comment]
Hi,

Now I get it :).

For instance, a self-service user will see his/her tickets or these and the ones from their groups depending on the profile permissions.

The same applies to techs, but we've added the Assigned tickets to filter the ones relevant to logged user.

The "All Tickets" menu option, show all the tickets that a user can access. 

We can add multiple filters, Group tickets, etc. Advanced Filtering will probably need a custom API request or more fine-grained filtering options, like the ones present in GLPI, but in my opinion, this is overkill for Mobile App.

To make things harder, we need multiple requests to get information about ticket actors, one for users, one for groups, one for suppliers.

Either way, additional development is needed, and most probably will need to be sponsored.

Cheers,

**Comment by OscarBeiro** [comment]
Hi,
We have just implemented a Saved Searches feature on Gapp 2 that should fix this and your future filtering needs.
It is currently a beta, but we have tested it intensively on our internal app.
Regards,
