### ISSUE TITLE
Connection out since i migrate my server

### ISSUE THREAD

**Issue by SwingJudge** [ticgal/gapp#32]
RTFM before opening an issue (Friendly reminder :)): https://tic.gal/gapp/
If you have not find a solution please add the information below.
---

**Describe the bug**

HI,
we use GAPP since 2 years ago, and since we have moved our server on a new hosting platform, we can't connect by the application GAPP.
I verify all parameters, API in GLPI and account in Gapp application, and i always have the same message, see attached (in french)

![Screenshot_20220125-170658](https://user-images.githubusercontent.com/45215079/151013965-27a019c0-d5f4-4c7b-8d9e-cb7d4b49f2d5.png)

I try to test this by the the Glpi Api Tool express 1.0.0, and it's the same thing.

I'm blocked, and if you can halp me, it will be nice.

Thanks

**To Reproduce**

**Expected behavior**

**Screenshots**

**Smartphone (please complete the following information):**

 - Device: Google Pixel 5 or Huawei P20
 - OS: Androïd 12

**Your GLPI server**

 - GLPI Version: 9.5.5
 - Installed plugins: gappessentials - datainjection
 
**GAT X report**

Please download: [GAT X](https://tic.gal/en/project/gat/) 
Attach generated file
i test with this tool, but i don't have txt file created

**Additional context**

**Comment by carlosbayerl** [comment]
I have the same problem. I'm looking forward to the solution.

**Comment by SwingJudge** [comment]
Hi Carlos, 

i have resolved my problem, but i can't tell you exactly why.

I know that it's the PHP version that need to be depreciated, it's my hosting support who find it.

Good evening

**Comment by OscarBeiro** [comment]
We've found some issues related to the PHP versions but did not have the time to confirm it.
Most likely to work versions  are 7.4 for Gapp Essentials and 8.0 for Gapp eXtended.
We'll look into it when we update the plugin to GLPI 10.
Regards.
