### ISSUE TITLE
Black screen just after credentials and APP stop working On my Android phone

### ISSUE THREAD

**Issue by Hermax1** [ticgal/gapp#33]
RTFM before opening an issue (Friendly reminder :)): https://tic.gal/gapp/
If you have not find a solution please add the information below.
---

I'm starting to install for test Android App Version 1.4.0-Selfservice.
Configuration of URL server is ok, protocole is https
then when i'm trying to connect just after the credential my phone screen goes black and the App stop running after few seconds

On the server side I can see in the logs that I'm tried to connect from IP XXX.XXX.XX...

I 've tested from another phone and that the same issue.

Any Idea ?

![1](https://user-images.githubusercontent.com/101327635/157644696-7818e229-f729-45ef-be8e-957679da30f9.png)

![2](https://user-images.githubusercontent.com/101327635/157644718-a6b578fd-dfce-4404-a631-5fe00e711019.png)

**Comment by OscarBeiro** [comment]
Hi,
This seems to be related to some tweaking on your GLPI API, and the app not expecting the values it is sending.
Only GLPI 9.5 is supported.

Anyway, we will soon release a new beta, please join the beta channel to test and report. 

Regards,

**Comment by OscarBeiro** [comment]
Hi,
The beta is out.
Please test and reopen if necessary.
Regards,
