### ISSUE TITLE
Modelo de solução filhos

### ISSUE THREAD

**Issue by gelsoniezzi** [ticgal/gapp#35]
<p><a href="https://github.com/ticgal/gapp/issues/35">https://github.com/ticgal/gapp/issues/35</a></p><p>The "<strong>></strong>" symbol is being replaced by <strong>\></strong>.</p><p>Ticket > Cetegory and Local</p>
<blockquote>GLPI ticket number: <a href='https://xes.ticgal.com/index.php?redirect=ticket_9406' rel='nofollow'>9406</a><br/>Created with <a href='https://tic.gal'>GitSync</a> in GLPI by Óscar Beiro</blockquote>

**Comment by gelsoniezzi** [comment]
![Elétrica its ok](https://user-images.githubusercontent.com/6624897/165114250-fa5f2bf6-51db-422d-9f95-f19e43973e62.jpeg)

**Comment by OscarBeiro** [comment]
Hi,
We will soon release a new beta, and it should be solved. Please join the beta channel.
Regards,

**Comment by gelsoniezzi** [comment]
Thank you!

**Comment by OscarBeiro** [comment]
Hi,
Beta is out. Please test, and report if not fixed.
Thanks.
Regards,

**Comment by gelsoniezzi** [comment]
Hi dear, is not fixet.
Version Beta 2.1.1 (0000275)
![WhatsApp Image 2022-06-30 at 11 01 29](https://user-images.githubusercontent.com/6624897/176697720-c0502ac3-ca07-4fdc-808e-c17a46218308.jpeg)

**Comment by gelsoniezzi** [comment]
The same problem is running on Task Templates 
![WhatsApp Image 2022-06-30 at 11 12 09](https://user-images.githubusercontent.com/6624897/176699595-9d67081a-21bb-4bc2-ba6c-8f8c6c99a7e2.jpeg)

**Comment by PedroTicGal** [comment]
Hi @gelsoniezzi ,

This should be fixed already in the current beta versión of Gapp.

Thank you again for your feedback!

Cheers.
