### ISSUE TITLE
Actor defined in the Task model field not defined as an actor

### ISSUE THREAD

**Issue by gelsoniezzi** [ticgal/gapp#36]
![image](https://user-images.githubusercontent.com/6624897/165531922-170a0b2e-313f-436a-b75b-4b90bb6a5e3e.png)

Actor defined in the Task model field not defined as an actor of the task registered in GAPP.

![image](https://user-images.githubusercontent.com/6624897/165534042-1a854159-53f4-46fd-a469-1aef95ca8562.png)

Add > Task;  Add > Model

**Comment by OscarBeiro** [comment]
Hi,
We have just released a new beta, and this issue should be fixed.
Please, feel free to reopen if it is not.
