### ISSUE TITLE
Gapp Essentials must be installed and active [Plugin]

### ISSUE THREAD

**Issue by caturputra** [ticgal/gapp#37]
<p><a href="https://github.com/ticgal/gapp/issues/37">https://github.com/ticgal/gapp/issues/37</a></p><p>I have install and activated Plugin GAPP Essential but when i want to login using GAPP Android client always show that gapp essentials must be installed and active.</p><p><img src="https://user-images.githubusercontent.com/8774702/174212582-87ca00cf-2620-4946-8bdd-0c03cb7da256.jpeg" alt="photo1655431997" /></p><p>Gapp version: 2.1.0 GLPI version: 10.0.1 Gapp Essentials version: 2.0.1</p><p><img src="https://user-images.githubusercontent.com/8774702/174212325-949b32c9-a032-4dd7-8b18-6c8d3f90db4c.png" alt="GAPP Essentials" /></p><p>Device: Poco X3 NFC OS: Android Ver 11</p><p>Any solution for this?</p><p><br />Created by caturputra</p>
<blockquote>GLPI ticket number: <a href='https://xes.ticgal.com/index.php?redirect=ticket_10224' rel='nofollow'>10224</a><br/>Created with <a href='https://tic.gal'>GitSync</a> in GLPI by Pedro Muñoz</blockquote>

**Comment by PedroTicGal** [comment]
Hi @caturputra,

First of all, thank you for using Gapp and providing us feedback :)

We are going to make some tests to see if we can replicate this behavior with a clean GLPI installation.

We will come to you with more information as soon as we discover something about this.

Cheers.

**Comment by PedroTicGal** [comment]
Hi @caturputra,

We have added a new feature to Gapp to help any user having problems with the server connection.

This feature have been included in version 2.1.1 (0000275) of Gapp and enables a new screen to help diagnose server connections.

To open this screen you have to:

- Go to settings screen.
- Long-press the "about" icon.

![Screenshot_20220627-124532](https://user-images.githubusercontent.com/48908942/175937970-b3c897db-fdd3-4a07-b345-2c97b6905eec.jpg)

- Go to the new option "Selftest".
- Enter your credentials.

**Remember that you must set the server address before using this function.**
