### ISSUE TITLE
Error of connection -> [ListProfileParser] type ‘Null’ is not a subtype of type ‘String’ in type cast

### ISSUE THREAD

**Issue by SwingJudge** [ticgal/gapp#38]
<p><a href="https://github.com/ticgal/gapp/issues/38">https://github.com/ticgal/gapp/issues/38</a></p><p>Hi,</p><p>i can't connect to my profile, i have this error :</p><p><img src="https://user-images.githubusercontent.com/45215079/190986944-23574b51-e761-4447-a052-69bd1b950ab7.png" alt="Screenshot_20220916-164848" /></p><p>I try with GLPI user by default, and it's fonctionnal.</p><p>Can you help me please?</p><p>GLPI 9.5.5 GAPP 2.2.0 (0000289)</p><p><br />Created by SwingJudge</p>
<blockquote>GLPI ticket number: <a href='https://xes.ticgal.com/index.php?redirect=ticket_11188' rel='nofollow'>11188</a><br/>Created with <a href='https://tic.gal'>GitSync</a> in GLPI by Óscar Beiro</blockquote>

**Comment by PedroTicGal** [comment]
Hi @SwingJudge ,

First of all, thank you for using Gapp and providing us feedback :)

We have added a new feature to Gapp to help any user having issues with the server connection.

This feature enables a new screen to help diagnose server connections.

To open this screen you have to:

- Go to settings screen.
- Long-press the "about" icon.

![Screenshot_20220627-124532](https://user-images.githubusercontent.com/48908942/175937970-b3c897db-fdd3-4a07-b345-2c97b6905eec.jpg)

- Go to the new option "Selftest".
- Enter your credentials.

**Remember that you must set the server address before using this function.**

Could you send us this report to see where is the issue?

Cheers!

**Comment by SwingJudge** [comment]
Thanks Pedro for your help, i send you the report by mail ;)

**Comment by gitsyncuser** [comment]
<p>Ok, it seems we have found the issue.</p><p>As far as we can see with the information provided, in your \"Super-Admin\" profile, there is an entity assigned with no name, so the API returns a null instead.</p><p>Try to rename the entity with ID: 9 to a no-empty name (or remove this entity from this profile permissions) and let us know if it worked.</p><p>Cheers.</p><blockquote>Created with <a href='https://tic.gal'>GitSync</a> in GLPI by Pedro Muñoz</blockquote>

**Comment by SwingJudge** [comment]
Perfect, it's all good.

Thanks and nice work for this application

**Comment by PedroTicGal** [comment]
Thank you for using Gapp!

See you around =)
