### ISSUE TITLE
Cannot add followup on tickets via mobile app

### ISSUE THREAD

**Issue by RageshR007** [ticgal/gapp#4]
Hi Oscar...As a followup on to previous issue....Now i m able to log in and view the tickets...but i m getting below error every time ....also i cannot add followup as it shows error as below screenshots...But i can add solution and close the ticket if i ignore 'Document permission error"...This error coming up regardless of the tickets have documents or not.

![image](https://user-images.githubusercontent.com/56621454/67066211-1b2c0d80-f18f-11e9-896d-bb889df6f735.png)

![image](https://user-images.githubusercontent.com/56621454/67066215-22ebb200-f18f-11e9-8ef3-b904eebfa799.png)

**Comment by RageshR007** [comment]
Apache log 

137.97.124.55 - - [18/Oct/2019:10:11:15 +0530] "GET /octa-it/apirest.php/Ticket/2018093710?expand_dropdowns=true&with_documents=true HTTP/1.1" 200 2566 "-" "Dalvik/2.1.0 (Linux; U; Android 8.0.0; AUM-AL20 Build/HONORAUM-AL20)"
137.97.124.55 - - [18/Oct/2019:10:11:15 +0530] "GET /octa-it/apirest.php/Ticket/2018093710/Ticket_User/?expand_dropdowns=true HTTP/1.1" 200 629 "-" "Dalvik/2.1.0 (Linux; U; Android 8.0.0; AUM-AL20 Build/HONORAUM-AL20)"
137.97.124.55 - - [18/Oct/2019:10:11:16 +0530] "GET /octa-it/apirest.php/Ticket/2018093710/Group_ticket/?expand_dropdowns=true HTTP/1.1" 200 2 "-" "Dalvik/2.1.0 (Linux; U; Android 8.0.0; AUM-AL20 Build/HONORAUM-AL20)"
137.97.124.55 - - [18/Oct/2019:10:11:17 +0530] "GET /octa-it/apirest.php/Ticket/2018093710/itilsolution/?expand_dropdowns=true&order=DESC HTTP/1.1" 200 2 "-" "Dalvik/2.1.0 (Linux; U; Android 8.0.0; AUM-AL20 Build/HONORAUM-AL20)"
137.97.124.55 - - [18/Oct/2019:10:11:17 +0530] "GET /octa-it/apirest.php/Ticket/2018093710/TicketTask/?expand_dropdowns=true&order=DESC HTTP/1.1" 200 2 "-" "Dalvik/2.1.0 (Linux; U; Android 8.0.0; AUM-AL20 Build/HONORAUM-AL20)"
137.97.124.55 - - [18/Oct/2019:10:11:17 +0530] "GET /octa-it/apirest.php/Ticket/2018093710/Document_Item/?expand_dropdowns=true&order=DESC HTTP/1.1" 401 75 "-" "Dalvik/2.1.0 (Linux; U; Android 8.0.0; AUM-AL20 Build/HONORAUM-AL20)"
137.97.124.55 - - [18/Oct/2019:10:11:17 +0530] "GET /octa-it/apirest.php/Ticket/2018093710/TicketFollowup/?expand_dropdowns=true&order=DESC HTTP/1.1" 200 2 "-" "Dalvik/2.1.0 (Linux; U; Android 8.0.0; AUM-AL20 Build/HONORAUM-AL20)"
::1 - - [18/Oct/2019:10:11:23 +0530] "OPTIONS * HTTP/1.0" 200 - "-" "Apache/2.4.6 (CentOS) PHP/7.2.19 (internal dummy connection)"
137.97.124.55 - - [18/Oct/2019:10:11:36 +0530] "POST /octa-it/apirest.php/TicketFollowup HTTP/1.1" 400 21 "-" "Dalvik/2.1.0 (Linux; U; Android 8.0.0; AUM-AL20 Build/HONORAUM-AL20)"

**Comment by OscarBeiro** [comment]
Hi Ragesh,

Please, RTFM :)
https://tic.gal/en/project/gapp/

**Comment by RageshR007** [comment]
Hi Oscar..I had referred the manual...As mentioned on the manual tried to add followup with picture and documents still shows error...!..the interesting thing is documents and images adding via mobile app is visible in the web...but descriptions not adding on tickets.

**Comment by OscarBeiro** [comment]
Hi Ragesh,
We have detected a bug affecting GLPI 9.3. Please upgrade to the last version: 0.9.8.5 and test again.
Regards

**Comment by PedroTicGal** [comment]
This was fixed in version 0.9.8.4
