### ISSUE TITLE
Still having problems to access "Gapp Essentials must be installed and active [Plugin]"

### ISSUE THREAD

**Issue by FedeBock** [ticgal/gapp#40]
<p><a href="https://github.com/ticgal/gapp/issues/40">https://github.com/ticgal/gapp/issues/40</a></p><p>Hi @caturputra,</p><p>We have added a new feature to Gapp to help any user having problems with the server connection.</p><p>This feature have been included in version 2.1.1 (0000275) of Gapp and enables a new screen to help diagnose server connections.</p><p>To open this screen you have to:</p><ul><li>Go to settings screen.</li><li>Long-press the "about" icon.</li></ul><p><img src="https://user-images.githubusercontent.com/48908942/175937970-b3c897db-fdd3-4a07-b345-2c97b6905eec.jpg" alt="Screenshot_20220627-124532" /></p><ul><li>Go to the new option "Selftest".</li><li>Enter your credentials.</li></ul><p><strong>Remember that you must set the server address before using this function.</strong></p><p><em>Originally posted by @PedroTicGal in <a href="https://github.com/ticgal/gapp/issues/37#issuecomment-1167273909">https://github.com/ticgal/gapp/issues/37#issuecomment-1167273909</a></em></p><p><br />Created by FedeBock</p>
<blockquote>GLPI ticket number: <a href='https://xes.ticgal.com/index.php?redirect=ticket_11228' rel='nofollow'>11228</a><br/>Created with <a href='https://tic.gal'>GitSync</a> in GLPI by Óscar Beiro</blockquote>

**Comment by FedeBock** [comment]
Gapp 2.2.0
GLPI 9.5.5
Gapp Essential 1.3.0

In this Gapp version  there is no "Selftest" option in the Configuration menu. 

Any suggestions?
Regards

**Comment by FedeBock** [comment]
![Screenshot_20220920-110033](https://user-images.githubusercontent.com/114000140/191278273-620c7a2c-6503-4fbd-afa4-9ddbccc734ca.jpg)

**Comment by caturputra** [comment]
Hi @FedeBock, thanks in advance and in version 2.1.1 of gapp essentials plugin , I have no problem with server connection. I also did some configuration about https on my server which I haven't done before.

**Comment by FedeBock** [comment]
> Hi @FedeBock, thanks in advance and in version 2.1.1 of gapp essentials plugin , I have no problem with server connection. I also did some configuration about https on my server which I haven't done before.

So your recommendation is to upgrade Gapp Essentials to version 2.1.1.
I will do so and will back with the results.

**Comment by OscarBeiro** [comment]
Please let us know how it went @FedeBock 
Thanks

**Comment by FedeBock** [comment]
Still having problem. 
The 2.1.1 of gapp essentials plugin seems to be for GLPI 10.0,  I have GLPI 9.5
Any advice?
Regards

**Comment by PedroTicGal** [comment]
Hi @FedeBock,

We are planning to release a new version of Gapp Essentials, compatible with GLPI 9.5.9 soon (hopefully, next week).

We will let you know when it is released.

Thank you.

**Comment by PedroTicGal** [comment]
Hi @FedeBock,

There is a new version of Gapp Essentials on the marketplace.

Gapp Essentials 1.4.1 for GLPI 9.5.9 and above (only GLPI 9.x.x, not GLPI 10.x.x).
Gapp Essentials 2.1.1 for GLPI 10.0.3 and above.

Try it and, if the issue persist, please reopen this issue.

Thank you.

**Comment by wjtechinfo-gif** [comment]
estou com problema no glpi 11 

Gapp Essentials must be installed via Marketplace
