### ISSUE TITLE
Não estou conseguindo acesso o aplicativo após a nova atualização dele.

### ISSUE THREAD

**Issue by IlzoNeto** [ticgal/gapp#41]
<p><a href="https://github.com/ticgal/gapp/issues/41">https://github.com/ticgal/gapp/issues/41</a></p><p>Quando tento acessar o aplicativo, retorna o seguinte erro: FormatException: Unexpected character (at character 1 ) <br />Estou usando o GLPI como servidor.</p><p><br />Created by IlzoNeto</p>
<blockquote>GLPI ticket number: <a href='https://xes.ticgal.com/index.php?redirect=ticket_11284' rel='nofollow'>11284</a><br/>Created with <a href='https://tic.gal'>GitSync</a> in GLPI by Óscar Beiro</blockquote>

**Comment by PedroTicGal** [comment]
Hi @IlzoNeto,
Could you tell us which version of **Gapp** and **Gapp Essentials** are you using?
Thanks.

**Comment by PedroTicGal** [comment]
GLPI version too, please :)

**Comment by acnology** [comment]
Hello @PedroTicGal 
im using GLPI 9.5.5 its work with new Gapp Plugin ?
My versions:

Gapp Essentials: 1.2.0
GLPI: 9.5.5
Gapp app: 2.2

**Comment by PedroTicGal** [comment]
Hi @acnology ,

See attached link -> [changelog of Gapp Essentials plugin](https://github.com/ticgal/gappessentials/releases).

> **"Gapp 2 will only run on Gapp Essentials 1.3+"**

It seems you are using an old version of essentials plugin.

Update plugin to 1.3.0 and try again, please.

Thank you.

**Comment by IlzoNeto** [comment]
> Oi@IlzoNeto, Você poderia nos dizer qual versão do **Gapp** e do **Gapp Essentials** você está usando? Obrigado.

Plugin 1.3.0 e o App 2.2.0 glpi 9.5

**Comment by PedroTicGal** [comment]
Hi @IlzoNeto ,

Could you provide us the whole GLPI version number? 9.5.**X**

Thank you.

**Comment by IlzoNeto** [comment]
> Oi@IlzoNeto,
> 
> Você poderia nos fornecer o número completo da versão do GLPI? 9.5. **X**
> 
> Obrigada.

9.5.5

**Comment by gitsyncuser** [comment]
<p>Hi @IlzoNeto,</p><p>Could you please send us your GLPI <strong>PHP</strong> and <strong>SQL</strong> error logs to help us to see different solutions for your problem?</p>

<p>Thank you.</p><blockquote>Created with <a href='https://tic.gal'>GitSync</a> in GLPI by Pedro Muñoz</blockquote>

**Comment by PedroTicGal** [comment]
Hi @IlzoNeto,

We have released a new version of Gapp Essentials in the marketplace (version 2.0.2) and we think the problem is solved in this version.

If the problem is not solved, please reopen this issue.

Thank you.
