### ISSUE TITLE
Detalles con el inicio de sesion en la app

### ISSUE THREAD

**Issue by Realy97** [ticgal/gapp#42]
<p><a href="https://github.com/ticgal/gapp/issues/42">https://github.com/ticgal/gapp/issues/42</a></p><p>Hola. la versión de glpi se actualizó de 9.4.4 a la versión 10.0.0, anteriormente en la versión de la app funcionaba bien sin ningún problema, para actualizar a la nueva versión se cambió el servidor de ubuntu a windows y la También se cambió la IP del servidor, lo único que se hizo fue exportar la base de datos e instalar el glpi en windows, se mantuvo toda la información y demás configuraciones, solo se cambió la IP del resto de api e intentar hacer la conexión al celular pero me manda errores que aun no se como solucionar si alguien me pudiera apoyar se los agradecere infinitamente.<br />Actual mente realice una instalacion de cero con la version 10.0.3 del glpi y ni asi puedo ingresar la url que utilizo ahora para pruebas es local y trato de concectar mi telefono a la nueva version del app y solo me devuelve errores mencionados pero por ejemplo si lo hago con la version anterior de app si puedo ingresar. De hecho en el registro aparece que inicie sesion pero sin abrir la app . <br />Algunos de los errores que me marca la aplicación.</p><p>Error FormatException: carácter inesperado (en el carácter 1), <br />aplicación</p><p>Este error lo muestra cuando escribo la url con api. ERROR_LOGIN_PARAMETERS_MISSING faltan el(los) parámetro(s) usuario, contraseña o user_token; vea la documentación en su navegador en <a href="http://xxxxxxx/glpi/apirest.php/">http://xxxxxxx/glpi/apirest.php/</a> #ERROR_LOGIN_PARAMETERS_MISSING</p><p><img src="https://user-images.githubusercontent.com/33636630/192109182-df19a90e-d47e-4b79-8aa9-cce1d470590c.jpeg" alt="WhatsApp Image 2022-09-24 at 11 38 56 AM" /></p><p><br />Created by Realy97</p>
<blockquote>GLPI ticket number: <a href='https://xes.ticgal.com/index.php?redirect=ticket_11304' rel='nofollow'>11304</a><br/>Created with <a href='https://tic.gal'>GitSync</a> in GLPI by Óscar Beiro</blockquote>

**Comment by PedroTicGal** [comment]
Hola @Realy97,

Podrías pasarnos la siguiente información:

- **Versión de GLPI**
p.e: GLPI 9.5.5 (Toda la numeración, no solo GLPI 9.5 o GLPI 10)
- **Versión de Gapp**
p.e: Gapp 2.2.0 (0000290)
- **Versión del plugin Essentials**
p.e: Essentials 1.3.0 or 2.0.1

Gracias.

---

Hi @Realy97,

Could you provide us your:

- **GLPI version.**
i.e: GLPI 9.5.5 (The complete version number, not just GLPI 9.5 or GLPI 10)
- **Gapp version.**
i.e: Gapp 2.2.0 (0000290)
- **Essentials plugin version.**
i.e: Essentials 1.3.0 or 2.0.1

Thank you.

**Comment by Realy97** [comment]
Hola les paso la información solicitada

**Versión de GLPI**
 GLPI 10.0.3
**Versión de Gapp**
 Gapp 2.2.0 (0000289)
**Versión del plugin Essentials**
 Essentials 2.0.1

**Comment by PedroTicGal** [comment]
Hola @Realy97,

Podrías por favor enviarnos los logs de errores de PHP y SQL de tu GLPI para ver cuál es la causa de este problema y poder ver cómo solucionarlo?

Muchas gracias.

<hr>

Hi @Realy97,

Could you please send us your GLPI PHP and SQL error logs to help us to see different solutions for your problem?

![6331590568fa99 86595214image_paste1263413](https://user-images.githubusercontent.com/48908942/192448690-09316d6a-7d5d-4185-95e5-fc6f8a7eb80e.png)

Thank you.

**Comment by Realy97** [comment]
Hola aqui envio el log de php, de sql no tengo como tal un registro o por lo menos no encontre alguno entre las carpetas si me pudieran indicar en donde lo puedo encontrar  esta es la ruta que segui y encontre el de php  glpi/files/_log/

[php-errors.log](https://github.com/ticgal/gapp/files/9656993/php-errors.log)

**Comment by gitsyncuser** [comment]
<p>Hi,</p><p>In order to help you, we need additional information about your GLPI instance. Please, go to:</p><p><code><em>Setup > General > System > Information about system installation and configuration</em></code></p><p>Depending on you GLPI version you can:</p><ul><li>Select the info between the code tags</li><li>Click on the <code>Copy system information</code> button</li></ul><p>Regards, </p><blockquote>Created with <a href='https://tic.gal'>GitSync</a> in GLPI by Óscar Beiro</blockquote>

**Comment by Realy97** [comment]
Hola, Espero que la informacion sea la solicitada
<details><summary>Información sobre instalación y configuración de sistema</summary><pre>GLPI 10.0.3 (/glpi => C:\xampp\htdocs\glpi)
Installation mode: TARBALL
Current language:es_MX

</details><details><summary>Server</summary><pre> 
Operating system: Windows NT DESKTOP-9QIVU8V 10.0 build 19044 (Windows 10) AMD64
PHP 8.1.6 apache2handler (Core, PDO, Phar, Reflection, SPL, SimpleXML, apache2handler, bcmath, bz2, calendar, ctype, curl, date,
	dom, exif, fileinfo, filter, ftp, gd, gettext, hash, iconv, intl, json, libxml, mbstring, mysqli, mysqlnd, openssl, pcre,
	pdo_mysql, pdo_sqlite, readline, session, standard, tokenizer, xml, xmlreader, xmlwriter, zip, zlib)
Setup: max_execution_time="120" memory_limit="512M" post_max_size="512M" safe_mode="" session.save_handler="files"
	upload_max_filesize="512M" 
Software: Apache/2.4.53 (Win64) OpenSSL/1.1.1n PHP/8.1.6 (Apache/2.4.53 (Win64) OpenSSL/1.1.1n PHP/8.1.6 Server at localhost
	Port 80
)
	Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/105.0.0.0 Safari/537.36
Server Software: mariadb.org binary distribution
	Server Version: 10.4.24-MariaDB
	Server SQL Mode: NO_ZERO_IN_DATE,NO_ZERO_DATE,NO_ENGINE_SUBSTITUTION
	Parameters: root@localhost/glpi
	Host info: localhost via TCP/IP
	
PHP version (8.1.6) is supported.
Sessions configuration is OK.
Allocated memory is sufficient.
mysqli extension is installed.
Following extensions are installed: dom, fileinfo, json, simplexml.
curl extension is installed.
gd extension is installed.
intl extension is installed.
libxml extension is installed.
zlib extension is installed.
The constant SODIUM_CRYPTO_AEAD_XCHACHA20POLY1305_IETF_NPUBBYTES is present.
Database engine version (10.4.24) is supported.
The log file has been created successfully.
Write access to C:\xampp\htdocs\glpi/files/_cache has been validated.
Write access to C:\xampp\htdocs\glpi/config has been validated.
Write access to C:\xampp\htdocs\glpi/files/_cron has been validated.
Write access to C:\xampp\htdocs\glpi/files has been validated.
Write access to C:\xampp\htdocs\glpi/files/_dumps has been validated.
Write access to C:\xampp\htdocs\glpi/files/_graphs has been validated.
Write access to C:\xampp\htdocs\glpi/files/_lock has been validated.
Write access to C:\xampp\htdocs\glpi/files/_pictures has been validated.
Write access to C:\xampp\htdocs\glpi/files/_plugins has been validated.
Write access to C:\xampp\htdocs\glpi/files/_rss has been validated.
Write access to C:\xampp\htdocs\glpi/files/_sessions has been validated.
Write access to C:\xampp\htdocs\glpi/files/_tmp has been validated.
Write access to C:\xampp\htdocs\glpi/files/_uploads has been validated.
Web access to files directory is protected
PHP directive "session.cookie_httponly" should be set to "on" to prevent client-side script to access cookie values.
exif extension is installed.
ldap extension is not present.
openssl extension is installed.
zip extension is installed.
bz2 extension is installed.
Zend OPcache extension is not present.
Following extensions are installed: ctype, iconv, mbstring.
Following extensions are not present: sodium.
Write access to C:\xampp\htdocs\glpi/marketplace has been validated.
Timezones seems not loaded, see https://glpi-install.readthedocs.io/en/latest/timezones.html.

</details><details><summary>GLPI constants</summary><pre> 
GLPI_ROOT: C:\xampp\htdocs\glpi
GLPI_CONFIG_DIR: C:\xampp\htdocs\glpi/config
GLPI_VAR_DIR: C:\xampp\htdocs\glpi/files
GLPI_MARKETPLACE_DIR: C:\xampp\htdocs\glpi/marketplace
GLPI_USE_CSRF_CHECK: 1
GLPI_CSRF_EXPIRES: 7200
GLPI_CSRF_MAX_TOKENS: 100
GLPI_USE_IDOR_CHECK: 1
GLPI_IDOR_EXPIRES: 7200
GLPI_ALLOW_IFRAME_IN_RICH_TEXT: 


Warning:  Array to string conversion in C:\xampp\htdocs\glpi\src\Config.php on line 2073

GLPI_SERVERSIDE_URL_ALLOWLIST: Array
GLPI_TELEMETRY_URI: https://telemetry.glpi-project.org
GLPI_INSTALL_MODE: TARBALL
GLPI_NETWORK_MAIL: glpi@teclib.com
GLPI_NETWORK_SERVICES: https://services.glpi-network.com
GLPI_MARKETPLACE_ALLOW_OVERRIDE: 1
GLPI_MARKETPLACE_MANUAL_DOWNLOADS: 1
GLPI_USER_AGENT_EXTRA_COMMENTS: 
GLPI_DISABLE_ONLY_FULL_GROUP_BY_SQL_MODE: 1
GLPI_AJAX_DASHBOARD: 1
GLPI_CALDAV_IMPORT_STATE: 0
GLPI_DEMO_MODE: 0
GLPI_CENTRAL_WARNINGS: 1
GLPI_DOC_DIR: C:\xampp\htdocs\glpi/files
GLPI_CACHE_DIR: C:\xampp\htdocs\glpi/files/_cache
GLPI_CRON_DIR: C:\xampp\htdocs\glpi/files/_cron
GLPI_DUMP_DIR: C:\xampp\htdocs\glpi/files/_dumps
GLPI_GRAPH_DIR: C:\xampp\htdocs\glpi/files/_graphs
GLPI_LOCAL_I18N_DIR: C:\xampp\htdocs\glpi/files/_locales
GLPI_LOCK_DIR: C:\xampp\htdocs\glpi/files/_lock
GLPI_LOG_DIR: C:\xampp\htdocs\glpi/files/_log
GLPI_PICTURE_DIR: C:\xampp\htdocs\glpi/files/_pictures
GLPI_PLUGIN_DOC_DIR: C:\xampp\htdocs\glpi/files/_plugins
GLPI_RSS_DIR: C:\xampp\htdocs\glpi/files/_rss
GLPI_SESSION_DIR: C:\xampp\htdocs\glpi/files/_sessions
GLPI_TMP_DIR: C:\xampp\htdocs\glpi/files/_tmp
GLPI_UPLOAD_DIR: C:\xampp\htdocs\glpi/files/_uploads
GLPI_INVENTORY_DIR: C:\xampp\htdocs\glpi/files/_inventories
GLPI_NETWORK_REGISTRATION_API_URL: https://services.glpi-network.com/api/registration/
GLPI_MARKETPLACE_PLUGINS_API_URI: https://services.glpi-network.com/api/glpi-plugins/
GLPI_I18N_DIR: C:\xampp\htdocs\glpi/locales
GLPI_VERSION: 10.0.3
GLPI_SCHEMA_VERSION: 10.0.3@a130db99c7d9b131c2e2ea59fe0d6260fe93d831
GLPI_MARKETPLACE_PRERELEASES: 
GLPI_MIN_PHP: 7.4.0
GLPI_MAX_PHP: 8.3.0
GLPI_YEAR: 2022

</details><details><summary>Libraries</summary><pre> 
htmlawed/htmlawed version 1.2.9 in (C:\xampp\htdocs\glpi\vendor\htmlawed\htmlawed)
phpmailer/phpmailer version 6.6.0 in (C:\xampp\htdocs\glpi\vendor\phpmailer\phpmailer\src)
simplepie/simplepie version 1.5.8 in (C:\xampp\htdocs\glpi\vendor\simplepie\simplepie\library)
tecnickcom/tcpdf version 6.5.0 in (C:\xampp\htdocs\glpi\vendor\tecnickcom\tcpdf)
michelf/php-markdown in (C:\xampp\htdocs\glpi\vendor\michelf\php-markdown\Michelf)
true/punycode in (C:\xampp\htdocs\glpi\vendor\true\punycode\src)
iamcal/lib_autolink in (C:\xampp\htdocs\glpi\vendor\iamcal\lib_autolink)
sabre/dav in (C:\xampp\htdocs\glpi\vendor\sabre\dav\lib\DAV)
sabre/http in (C:\xampp\htdocs\glpi\vendor\sabre\http\lib)
sabre/uri in (C:\xampp\htdocs\glpi\vendor\sabre\uri\lib)
sabre/vobject in (C:\xampp\htdocs\glpi\vendor\sabre\vobject\lib)
laminas/laminas-i18n in (C:\xampp\htdocs\glpi\vendor\laminas\laminas-i18n\src)
laminas/laminas-servicemanager in (C:\xampp\htdocs\glpi\vendor\laminas\laminas-servicemanager\src)
monolog/monolog in (C:\xampp\htdocs\glpi\vendor\monolog\monolog\src\Monolog)
sebastian/diff in (C:\xampp\htdocs\glpi\vendor\sebastian\diff\src)
donatj/phpuseragentparser in (C:\xampp\htdocs\glpi\vendor\donatj\phpuseragentparser\src\UserAgent)
elvanto/litemoji in (C:\xampp\htdocs\glpi\vendor\elvanto\litemoji\src)
symfony/console in (C:\xampp\htdocs\glpi\vendor\symfony\console)
scssphp/scssphp in (C:\xampp\htdocs\glpi\vendor\scssphp\scssphp\src)
laminas/laminas-mail in (C:\xampp\htdocs\glpi\vendor\laminas\laminas-mail\src\Protocol)
laminas/laminas-mime in (C:\xampp\htdocs\glpi\vendor\laminas\laminas-mime\src)
rlanvin/php-rrule in (C:\xampp\htdocs\glpi\vendor\rlanvin\php-rrule\src)
blueimp/jquery-file-upload in (C:\xampp\htdocs\glpi\vendor\blueimp\jquery-file-upload\server\php)
ramsey/uuid in (C:\xampp\htdocs\glpi\vendor\ramsey\uuid\src)
psr/log in (C:\xampp\htdocs\glpi\vendor\psr\log\Psr\Log)
psr/simple-cache in (C:\xampp\htdocs\glpi\vendor\psr\simple-cache\src)
psr/cache in (C:\xampp\htdocs\glpi\vendor\psr\cache\src)
league/csv in (C:\xampp\htdocs\glpi\vendor\league\csv\src)
mexitek/phpcolors in (C:\xampp\htdocs\glpi\vendor\mexitek\phpcolors\src\Mexitek\PHPColors)
guzzlehttp/guzzle in (C:\xampp\htdocs\glpi\vendor\guzzlehttp\guzzle\src)
guzzlehttp/psr7 in (C:\xampp\htdocs\glpi\vendor\guzzlehttp\psr7\src)
glpi-project/inventory_format in (C:\xampp\htdocs\glpi\vendor\glpi-project\inventory_format\lib\php)
wapmorgan/unified-archive in (C:\xampp\htdocs\glpi\vendor\wapmorgan\unified-archive\src)
paragonie/sodium_compat in (C:\xampp\htdocs\glpi\vendor\paragonie\sodium_compat\src)
symfony/cache in (C:\xampp\htdocs\glpi\vendor\symfony\cache)
html2text/html2text in (C:\xampp\htdocs\glpi\vendor\html2text\html2text\src)
symfony/css-selector in (C:\xampp\htdocs\glpi\vendor\symfony\css-selector)
symfony/dom-crawler in (C:\xampp\htdocs\glpi\vendor\symfony\dom-crawler)
twig/twig in (C:\xampp\htdocs\glpi\vendor\twig\twig\src)
twig/string-extra in (C:\xampp\htdocs\glpi\vendor\twig\string-extra)
symfony/polyfill-ctype not found
symfony/polyfill-iconv not found
symfony/polyfill-mbstring not found
symfony/polyfill-php80 not found
symfony/polyfill-php81 not found
symfony/polyfill-php82 in (C:\xampp\htdocs\glpi\vendor\symfony\polyfill-php82)

</details><details><summary>SQL replicas</summary><pre> 
Not active

</details><details><summary>Notifications</summary><pre> 
Way of sending emails: PHP

</details><details><summary>Plugins list</summary><pre> 
	barcode              Name: Barcode                        Version: 2.7.1      State: Enabled                                 
		Install Method: Marketplace
	gappessentials       Name: Gapp Essentials                Version: 2.0.1      State: Enabled                                 
		Install Method: Marketplace
	metabase             Name: metabase                       Version: 1.3.0      State: Installed / not activated               
		Install Method: Marketplace

</pre></details>

**Comment by PedroTicGal** [comment]
Hi @Realy97,

We have released a new version of Gapp Essentials in the marketplace (version 2.0.2) and we think the problem is solved in this version.

If the problem is not solved, please reopen this issue.

Thank you.

**Comment by Realy97** [comment]
Hola  buenos dia
Ya realice el procedimiento para configurar pero aun asi sigo teniendo el mismo problema no me deja.
Lo primero que hice fue descargar el plugin del mercado ahora tengo la version 
![image](https://user-images.githubusercontent.com/33636630/194357972-9ed5f8af-aaa4-47b6-a9c6-8107b98024db.png)

sin embargo aun he podido ingresar por ejemplo en le url de la api 
![WhatsApp Image 2022-10-06 at 10 47 22 AM (1)](https://user-images.githubusercontent.com/33636630/194359413-4de06237-2485-4545-9c2d-b1419ac1bf94.jpeg)

y me marca este error al ingresar usuario y contraseña
![WhatsApp Image 2022-10-06 at 10 47 22 AM](https://user-images.githubusercontent.com/33636630/194359936-a456ceaa-3baf-49af-a489-c21dfe823c00.jpeg)

si ingreso la siguiente url 
![WhatsApp Image 2022-10-06 at 10 47 23 AM](https://user-images.githubusercontent.com/33636630/194360123-1a92f9e2-8e0a-44be-a89a-9d7e583d6f6e.jpeg)
 me marca este error 
![WhatsApp Image 2022-10-06 at 10 47 23 AM (1)](https://user-images.githubusercontent.com/33636630/194360213-628a70eb-36f1-4575-9e40-ac5e197b01c5.jpeg)

Estoy utilizado como servidor local con xammp de Apache/2.4.53 (Win64) OpenSSL/1.1.1n PHP/8.1.6
Versión del servidor: 10.4.24-MariaDB 

Como comente es una instalacion del glpi en limpio y no me permite ingresar . si me pudieran apoyar
