### ISSUE TITLE
Problema con el error  ERROR_SESSION_TOKEN_MISSSING

### ISSUE THREAD

**Issue by IsraeVelez** [ticgal/gapp#44]
Hola a todos, espero puedan ayudarme
cuando quiero iniciar sesion en GAPP sale el error "ERROR_SESSION_TOKEN_MISSSING"  
La versionde mi GLPI es 10.0.3 
version de GAPP es la  2.2.0 (0000289) Beta
Version de GAPP Essentials  2.0.1
Agrego una foto del error :)
![Screenshot_20220927_151019](https://user-images.githubusercontent.com/80785403/192626111-4d51bf55-1ab7-4453-8ecb-b6b5a61a362b.jpg)

**Comment by Realy97** [comment]
Hola @IsraeVelez  yo igual tengo ese problema con la app espero haya alguna solución para ese detalle.

**Comment by gitsyncuser** [comment]
Hi,

Could you please send us your:

- GLPI version i.e.: GLPI 9.5.5 (The complete version number, not just GLPI 9.5 or GLPI 10)
- Gapp version i.e.: Gapp 2.2.0 (0000290)
- Gapp Essentials plugin version i.e: Essentials 1.3.0 or 2.0.1
- OS version i.e.: Ubuntu 22.04 
- Webserver version i.e.: Apache 2.4.

Thank you.

**Comment by OscarBeiro** [comment]
Hi,
Please check this KB article:
https://tic.gal/es/error_app_token_parameters_missing-conectandose-a-la-api-de-glpi/

**Comment by IsraeVelez** [comment]
Thanks for help me I already solved the problem by installing glpi in a docker compose and in gcp

**Comment by OscarBeiro** [comment]
It is usually a GLPI misconfiguration and hard to debug from our side.
Thanks for the feedback.
