### ISSUE TITLE
Gapp 1.4.1 apk

### ISSUE THREAD

**Issue by FedeBock** [ticgal/gapp#45]
.Does anybody have a secure link to download teg Gapp version 1.4.1?
I probe the 2.0 and doesn't work for me, but the old version is still working for the technician that doesnt upgrade. Unfortunately I couldn't found a secure link to download and downgrade to the previous version of Gapp.
Please help me whit a link or the apk file.
Regards

**Comment by OscarBeiro** [comment]
Hi,
Sorry, we have discontinued the 1.X development completely.
In fact, we warn it on the 1.4.1 version.
If you have an issue, please open a ticket detailing all your software and OS versions and a way to reproduce it. 
Regards,
