### ISSUE TITLE
Seguimiento con el inicio de sesion que no permite abrirlo con la app

### ISSUE THREAD

**Issue by Realy97** [ticgal/gapp#46]
Hola 
Ya realice el procedimiento para configurar pero aun asi sigo teniendo el mismo problema no me deja.
Lo primero que hice fue descargar el plugin del mercado ahora tengo la version 
![image](https://user-images.githubusercontent.com/33636630/194357972-9ed5f8af-aaa4-47b6-a9c6-8107b98024db.png)

sin embargo aun he podido ingresar por ejemplo en le url de la api 
![WhatsApp Image 2022-10-06 at 10 47 22 AM (1)](https://user-images.githubusercontent.com/33636630/194359413-4de06237-2485-4545-9c2d-b1419ac1bf94.jpeg)

y me marca este error al ingresar usuario y contraseña
![WhatsApp Image 2022-10-06 at 10 47 22 AM](https://user-images.githubusercontent.com/33636630/194359936-a456ceaa-3baf-49af-a489-c21dfe823c00.jpeg)

si ingreso la siguiente url 
![WhatsApp Image 2022-10-06 at 10 47 23 AM](https://user-images.githubusercontent.com/33636630/194360123-1a92f9e2-8e0a-44be-a89a-9d7e583d6f6e.jpeg)
 me marca este error 
![WhatsApp Image 2022-10-06 at 10 47 23 AM (1)](https://user-images.githubusercontent.com/33636630/194360213-628a70eb-36f1-4575-9e40-ac5e197b01c5.jpeg)

Estoy utilizado como servidor local con xammp de Apache/2.4.53 (Win64) OpenSSL/1.1.1n PHP/8.1.6
Versión del servidor: 10.4.24-MariaDB 

Como comente es una instalacion del glpi en limpio y no me permite ingresar . si me pudieran apoyar

_Originally posted by @Realy97 in https://github.com/ticgal/gapp/issues/42#issuecomment-1270341581_

**Comment by PedroTicGal** [comment]
Hola @Realy97,

Afortunadamente ya hemos localizado el problema y mientras escribo esto, mis compañeros están haciendo un nuevo release de Gapp Essentials.

Si deseas obtenerlo antes de que lancemos este release públicamente, puedes ir al siguiente issue y aplicar el parche que mi compañero Xacobo (xacobofg) facilita en el mismo.

https://github.com/ticgal/gappessentials/issues/38#issuecomment-1281084930

Muchas gracias.

PD: Recuerda que en la dirección del servidor hay que poner la de GLPI **sin la parte del apirest.php**
