### ISSUE TITLE
gapp 2.2.1 boton de configuracion cambio por condiciones de servicio 

### ISSUE THREAD

**Issue by jorgepn** [ticgal/gapp#47]
gapp 2.2.1 boton de configuracion cambio por condiciones de servicio ,
presiono el boton y no hace nada, no aparece para configurar el servidor

![WhatsApp Image 2022-10-14 at 11 27 39 AM](https://user-images.githubusercontent.com/69011398/195906755-ffb5caf2-1ebc-48af-90c0-2bc7df5cf23a.jpeg)

**Comment by dalohuer2004** [comment]
Hola, también me ocurre lo mismo, tiene alguna solución en la opción beta??

**Comment by OscarBeiro** [comment]
Hi,

The "Solution" is **Accept the Service Conditions**.

Regards,

**Comment by PedroTicGal** [comment]
Hola @dalohuer2004 y @jorgepn,

Después de revisar este problema (parece que hay bastante gente a la que le sucede esto) finalmente hemos encontrado el motivo del error.

En nuestra página de traducciones parece que se tradujo incorrectamente la cadena de las "condiciones y términos de uso" y el código no era capaz de encontrar los puntos clave para parsear las url que redirigen a los términos.

Esto error sólo sucede cuando Gapp está configurado en el idioma "Español (argentina)". Hemos solucionado el fallo de traducción, pero mientras lanzamos una versión nueva si quieren que Gapp les funcione cambien manualmente el idioma a cualquier otro idioma excepto a "Español (Argentina)".

Disculpen las molestias y tengan buen día.
