### ISSUE TITLE
Selection of "Requester" and "Assigned to" on ticket creation

### ISSUE THREAD

**Issue by xris5** [ticgal/gapp#5]
I would like to take into consideration that when creating a new ticket, once the corresponding entity was selected, gave the option to choose the Requester and did not put by default the user (in this case would be a technician) who has the session initiated in the app. And the same case with what would be the assigned technicians (not only the user who uses the app), and even the Watcher .

In this way it would be useful if you have a nomadic helpdesk, which goes around the world opening tickets, could be assigned to the real requester at the moment, so that for example, the next level of support was the one that would charge the ticket.

**Comment by OscarBeiro** [comment]
Hola @xris5:

Thanks for using Gapp.
This project started as a Self-service app for end-users, and has grown up in very little time.

We take duly note of your requests for future releases. 

On ticket creation:
1. Assign requester (other than the logged user)
1. Assign technician
1. Assign watcher

Saludos :)

**Comment by OscarBeiro** [comment]
Hi,

Upcoming Gapp 1.1 will feature auto assign for watchers and techs.
We hope you find it useful.

Cheers,

**Comment by CartCaved** [comment]
Hi, is it possible to disable the assignment of tech. I'm the supervisor and I create tickets to be assigned to a specific person in the team or just for anyone available.

**Comment by OscarBeiro** [comment]
Hi @CartCaved,

This feature is on the roadmap waiting for someone to sponsor it. When the time comes it will be developed according to clients needs.
If you are interested please contact us at https://tic.gal/

Regards,

**Comment by dxdemetriou** [comment]
It will be useful when on the main ticket view is also visible the "assigned to" user (not the group), so to know which tickets are handled by others of the group. Or similar with the "Assigned Tickets" (all tickets assigned to other users but not to me)

**Comment by OscarBeiro** [comment]
Hi dxdemeitrou,

Sorry but I don't get it. Could you open another ticket and explain it in more detail? 

Thanks,

**Comment by OscarBeiro** [comment]
This feature will be released on the next Gapp version.
Thanks
