### ISSUE TITLE
detalle con actualizaciones 

### ISSUE THREAD

**Issue by Realy97** [ticgal/gapp#50]
Hola, nuevamente he realizado todo el proceso que me comentan, me percate de que ya habian realizado la actualizacion de la app de gapp y la del gapp essential, sin embargo sigo teniendo los mismo incovenientes, no se que sea lo que sucede. 
me marca los mismo.
![image](https://user-images.githubusercontent.com/33636630/198126412-b06d4d7b-4e2f-4e50-8283-228eb94bb370.png)

ya actualice la version del essential y del gapp, solo que con la app al momento de abrirla como que se atora y tengo que borrar los datos del cache y es ahi cuando me permite abrir la app y me aparece las politicas. 

y me percate de esto no se si me tenga algo que ver
![image](https://user-images.githubusercontent.com/33636630/198126922-e7f97229-8379-4b91-90d4-0be786c25495.png)

Si me pudieran apoyar. gracias

**Comment by PedroTicGal** [comment]
Hola @Realy97,

Nos podrías enviar el reporte de errores de Gapp y adjuntar al correo el número de issue para saber que es tuyo?

Aquí tienes las instrucciones -> https://github.com/ticgal/gapp/issues/37#issuecomment-1167273909

Además, nos podrías indicar qué versión de GLPI y Gapp Essentials (el plugin) usas?

Muchas gracias.

**Comment by Realy97** [comment]
Hola buen dia, ya eh enviado el correo con la informacion tambien si gustan puedo subirlo aqui para tener el registro de lo que sucede. 
Espero y me puedan apoyar. Se los agradecere infinitamente

**Comment by PedroTicGal** [comment]
Hola @Realy97,

Hemos recibido toda la información que nos has enviado. Elevo este caso a mis compañeros de desarrollo web ya que parece un problema con el plugin Gapp Essentials (y probablemente con Windows).

Te informaremos con lo que encontremos.

Un saludo.

**Comment by PedroTicGal** [comment]
Hola @Realy97,

Después de investigarlo con desarrollo web, llegamos a la conclusión que debe tratarse de una configuración erronea en su servidor web.

La petición que está haciendo que Gapp no funcione debidamente está funcionando correctamente, pero su servidor web está adjuntando al inicio de la respuesta código HTML que debería ir a los logs de PHP. Después de eso, está devolviendo la respuesta en json como debería.

De este modo, el parseador de json de Gapp no está entendiendo la respuesta a causa del HTML del principio y falla.

Compruebe la configuración de su servidor web, ya que este tipo de advertencias en HTML se suelen generar en los logs de PHP, no se sacan directamente con la respuesta a la petición.

Espero que con esta pista pueda solucionar sus problemas con Gapp.

No dude en consultarnos ante cualquier duda, y gracias por usar Gapp!
