### ISSUE TITLE
distorted image using Gapp with Glpi 10.0.3

### ISSUE THREAD

**Issue by rafacss** [ticgal/gapp#51]
Whenever I take a photo using the smartphone camera using the Gapp, the image seen in the Gapp is normal, but when I view it in the Glpi Web, whether horizontal or vertical, it is distorted and stretched.

I'm using Glpi 10.0.3 and Gapp 1.4 on my Android 12.

![image](https://user-images.githubusercontent.com/67194670/198740195-016ed439-faf6-419b-b183-ce71430cf580.png)

![image](https://user-images.githubusercontent.com/67194670/198740101-e1d07a3d-4506-4808-b9bd-10632b248a01.png)

![image](https://user-images.githubusercontent.com/67194670/198739947-79065e60-1d6a-439a-b50b-92e3ad3d268f.png)

**Comment by PedroTicGal** [comment]
Hi @rafacss,

We have seen this before. If you download and open this image on your computer, mobile device, etc... you will probably see the image without problems.

It seems to be a problem with the GLPI preview module and the EXIF properties.

Could you try Gapp 2 and let us know if you find any improvement?

Thank you.

**Comment by rafacss** [comment]
thanks for the feedback!  the problem occurs in Gapp version 2.2.2

**Comment by OscarBeiro** [comment]
Hi,

We have reviewed this issue, and it is GLPI related.
Your camera saves the image always horizontally and uses EXIF orientation to store the 90º Rotation.
This typically affects Samsung but not Huawei, for instance.

GLPI shows the thumbnail correctly, and if you click on it, the browser also considers EXIF.
Unfortunately, GLPI's PhotoSwipe - lightbox is not considering it.

You should open an issue on GLPI github or use your GLPI network to report it directly to Teclib'

We are closing as it is not related to Gapp.
Regards.
