### ISSUE TITLE
Widget Feature Suggestion for Android Smartphones

### ISSUE THREAD

**Issue by rafacss** [ticgal/gapp#52]
I would like to contribute a feature suggestion to the Gapp.

Widgets for Android Smartphones are very useful, I believe that a widget that allows you to view the number of new calls, assigned, pending and planned calls as a shortcut on the android screen would be amazing!

example:

![photo_2022-11-07_11-02-27](https://user-images.githubusercontent.com/67194670/200330472-5a7a6bff-a7b9-49ae-afa6-5342e951d061.jpg)

**Comment by OscarBeiro** [comment]
Hi,
Thank you for your suggestion. This feature has been on the roadmap for a while. 
We will continue to seek a sponsor.
Regards,

**Comment by OscarBeiro** [comment]
It will be added to  Gapp White Label 2.6
Regards
