### ISSUE TITLE
[Feature] On ticket resolution add an option so customer can provide their signature

### ISSUE THREAD

**Issue by dhrzic** [ticgal/gapp#54]
**Is your feature request related to a problem? Please describe.**
Feature request

**Describe the solution you'd like**
It would be affective and papperless if we had an option when ticket is being resolved, to enable tehnician to get/collect the signature from the customer. 
Option like an popup drawing editor (or something similar) so customer can add their signature to confirm ticket resolution. Tehnician would set the ticket status to resolved, where in order to confirm the realization of the ticket would open the option to add customers signature (if the customer is being satisfied with the resolution). Option would be the delivery service is having when customer receives the package and confirms receival.

**Additional context**
Example of how it would look like. 

![Snimka zaslona 2022-11-28 122410](https://user-images.githubusercontent.com/104624347/204266248-d46c9c6a-3880-495a-b162-3a732acc28cb.png)

**Comment by OscarBeiro** [comment]
Hi, 
This feature it's probably being sponsored soon, and will be added to Gapp White Label, since it needs backend development.
Regards,
