### ISSUE TITLE
I can't loggin

### ISSUE THREAD

**Issue by gelsoniezzi** [ticgal/gapp#55]
I can't loggin, the app does't show any error message.

![gapp](https://user-images.githubusercontent.com/6624897/205144638-b4be28eb-7e36-4426-8bb6-a29eab43b034.jpeg)

**Comment by OscarBeiro** [comment]
This is typically due to some misconfiguration on your GLPI or your environment.
If you can access the demo site, you need to debug it yourself.
Regards,
