### ISSUE TITLE
GAPP on 9.5.12

### ISSUE THREAD

**Issue by SilvaFernando** [ticgal/gapp#57]
Hello, I'm testing gapp on GLPI 9.5.12, but the playstore only has a version compatible with GLPI 10, where can I find a version for GLPI 9.5.12?

![image](https://user-images.githubusercontent.com/53239752/223479494-8be2cc3e-58d7-4d7d-a321-dc5f3b576eb4.png)

**Comment by OscarBeiro** [comment]
Hi, 
Gapp is no longer compatible with GLPI 9.5.X.
Be aware that July,1st GLPI 9.5.X will be discontinued by Teclib' and no security patches will be available.
Please, upgrade to GLPI 10.0.6 and enjoy Gapp.
Regards,
