### ISSUE TITLE
 Error accessing APP Gaap -  GLPI 10

### ISSUE THREAD

**Issue by alekyxander** [ticgal/gapp#59]
When trying to access the app it shows the error message
format exception unexpected character (at character 1) <br >

**Comment by OscarBeiro** [comment]
Hi,
Please check #58 and report back.
Regards,

**Comment by alekyxander** [comment]
Boa tarde, 
![image](https://user-images.githubusercontent.com/46962468/231857669-28cbf0e8-ceae-4b23-a4b0-9d931ae9d935.png)
mesmo com a instalação limpa ainda tenho este erro ao logar,

**Comment by alekyxander** [comment]
Estou na versão 10.7 do glpi, fiz o teste com aversão do gapp 1.4 e ele abre a aplicação, com a mesma instancia do GLPI

**Comment by alekyxander** [comment]
Erro encontrado no selftest 
![image](https://user-images.githubusercontent.com/46962468/231860602-cf3f711f-2cad-4420-a890-f93f8ed862c8.png)

**Comment by gitsyncuser** [comment]
<p>Good morning, </p>\r\n<p>The issue may be in the plugin Gapp Essentials you have installed in your GLPI, can you please tell us what version of it are you using please? </p>\r\n<p>Thank you very much,</p>\r\n<p>Regards</p><blockquote>Created with <a href='https://tic.gal'>GitSync</a> in GLPI by Fernando Estévez</blockquote>

**Comment by alekyxander** [comment]
Good morning, I'm using the latest version available on the marketplace 2.1.1
![image](https://user-images.githubusercontent.com/46962468/232024771-f460216d-740d-4b51-92ca-69a17f635a3e.png)

**Comment by alekyxander** [comment]
Bom dia, alguém pode me ajudar?

**Comment by OscarBeiro** [comment]
Please test the new Gapp Essentials version
Regards,
