### ISSUE TITLE
ERROR_LOGIN_PARAMETERS_MISSING

### ISSUE THREAD

**Issue by reinethernal** [ticgal/gapp#6]
**Describe the bug**
GAPP could not connect with an error related here
related issue
https://github.com/ticgal/gappessentials/issues/11
**To Reproduce**
1.Install app
2.Configure server URL on app
3.Try to login
4. see an error

**Expected behavior**
Login and use an app
**Screenshots**
![photo_2019-10-22_15-45-50](https://user-images.githubusercontent.com/35932698/67288927-6ffcba80-f4e6-11e9-8c00-f442c77b9ff1.jpg)
![photo_2019-10-22_15-51-35](https://user-images.githubusercontent.com/35932698/67290316-9cb1d180-f4e8-11e9-96ab-74f781fb1e01.jpg)

**Smartphone (please complete the following information):**
 - Device: [ASUS ze551ml]
 - OS: android 6.0.1

**Your GLPI server**
 - GLPI Version:9.4.4
 - Installed plugins:
fields               Name: Additionnal fields             Version: 1.9.1      State: Enabled
	impacts              Name: Asset impacts                  Version: 1.3.2      State: Enabled
	barcode              Name: Barcode                        Version: 2.4.0      State: Enabled
	manageentities       Name: Entities portal                Version: 3.1.0      State: Enabled
	formcreator          Name: Form Creator                   Version: 2.9.0-beta.1 State: Enabled
	fusioninventory      Name: FusionInventory                Version: 9.4.0+1.0  State: Enabled
	gappessentials       Name: Gapp Essentials                Version: 1.1.0      State: Enabled
	loginbyemail         Name: Login By E-mail                Version: 1.0.0      State: Not installed
	reservation          Name: Reservation                    Version: 2.1.3      State: Enabled
	room                 Name: Room Management                Version: 3.1.1      State: Enabled
	telegrambot          Name: TelegramBot                    Version: 3.0.0      State: To be cleaned
	satisfaction         Name: Больше вопросов для оценки удо Version: 1.4.0      State: Enabled
	itilcategorygroups   Name: Группы ITIL Категории     Version: 2.2.0      State: Enabled
	domains              Name: Домены                         Version: 2.1.0      State: Enabled
	moreticket           Name: Еще заявка                     Version: 1.5.0      State: Enabled
	consumables          Name: Заказ расходных материалов Version: 1.5.0      State: To be cleaned
	reports              Name: Отчеты                         Version: 1.13.0     State: Enabled
	dashboard            Name: Панель отчетов              Version: 0.9.6      State: Enabled
	pdf                  Name: Печать в PDF                   Version: 1.6.0      State: To be cleaned
	behaviors            Name: Поведения                      Version: 2.2.0      State: Enabled
	mreporting           Name: Подробные отчеты          Version: 1.6.1      State: Enabled
	news                 Name: Уведомления                   Version: 1.5.1      State: Enabled
	genericobject        Name: Управление объектами  Version: 2.7.0      State: Not installed

**Additional context**
curl requests work file, but i can't login with an app.

**Comment by reinethernal** [comment]
Here's additional screenshot made wirh packet capture software

**Comment by reinethernal** [comment]
https://yadi.sk/i/N7pX2JBXZlDdfA

**Comment by reinethernal** [comment]
Fixed

**Comment by OscarBeiro** [comment]
Hi, 
It would be great if you told us what was the problem on your side to help future users.
Regards,

**Comment by reinethernal** [comment]
> Hi,
> It would be great if you told us what was the problem on your side to help future users.
> Regards,

@OscarBeiro had to add 

<VirtualHost *:443>
X
X
X
X
SetEnvIf Authorization ".*" HTTP_AUTHORIZATION=$0

at config file

**Comment by OscarBeiro** [comment]
So you are using a PHP-FPM
Thanks for the feedback, we will add it to Known issues.
Спасибо :)

**Comment by reinethernal** [comment]
Thank you for such app) This is really helpfull. Can i add feature requests?

**Comment by OscarBeiro** [comment]
Be my guess.
I have just setup a Feature request template.
