### ISSUE TITLE
ERROR_APP_TOKEN_PARAMETERS_MISSING

### ISSUE THREAD

**Issue by jiritomanek85** [ticgal/gapp#60]
Hello, I need advice on how to remove the app token. Every time I delete it it gets restored. GLPI version 10.0.7. Thank you for your advice. 

Because because of this I can't login to GAPP ESSENTIALS

![image](https://github.com/ticgal/gapp/assets/11149271/e94e5a02-fdac-434f-b2f5-bdf6d81e42b5)

**Comment by gitsyncuser** [comment]
<p>Hi,</p>\r\n<p>A quick search in google should give you the answer.</p>\r\n<p>Anyway, here you have: https://tic.gal/en/error_app_token_parameters_missing-connecting-to-glpi-api/</p>\r\n<p> </p>\r\n<p>Regards</p><blockquote>Created with <a href='https://tic.gal'>GitSync</a> in GLPI by Óscar Beiro</blockquote>
