### ISSUE TITLE
Useful and necessary improvements

### ISSUE THREAD

**Issue by ak47d** [ticgal/gapp#64]
Hello! Gapp is an excellent mobile application, but it would become even better if the following improvements were made, which are sorely lacking:

1. Implement in GAPP the ability to customize or transfer template settings from GLPI for mandatory fields, title, description, ticket category.
2. Take into account access rights according to the user profile selected in GLPI in GAPP.
3. Implement the ability to change the category of an application in GAPP for profiles of technical specialists, similar to when creating an application.
4. Implement request source label settings in the GAPP or GLPI settings to identify incoming requests from GAPP.
5. When blocking the ability to change the status of applications in GLPI through the YAGP plugin or similar, this blocking does not work in GAPP

**Comment by OscarBeiro** [comment]
Hi, 
Thanks for your feedback. We will soon release 2.5 so we will take notes to add your requests to 2.6. But let's review them:

- [ ] Implement in GAPP the ability to customize or transfer template settings from GLPI for mandatory fields, title, description, ticket category.
This is a heavy development. We will take it into consideration but it is not prioritary unless somebody wishes to sponsor. Take into consideration end users have access to a very limited number of API endpoints.

- [ ] Take into account access rights according to the user profile selected in GLPI in GAPP.

We are currently taking this into consideration. It might be a bug, could you report your specific case?

- [ ] Implement the ability to change the category of an application in GAPP for profiles of technical specialists, similar to when creating an application.
It will be added to the roadmap.

- [ ] Implement request source label settings in the GAPP or GLPI settings to identify incoming requests from GAPP.

This is currently possible in Gapp White Label. We will see if we can port it easily to Gapp Self-Service.

- [ ] When blocking the ability to change the status of applications in GLPI through the YAGP plugin or similar, this blocking does not work in GAPP

Not sure about what you mean. Could you explain? Thanks.  Screenshots will help :)

**Comment by OscarBeiro** [comment]
Gapp 2.6 will provide some additional features.
Please open a new request with the missing ones.
Regards,
