### ISSUE TITLE
Error certificado SSL

### ISSUE THREAD

**Issue by brian-02** [ticgal/gapp#65]
Hola, estoy teniendo porblemas con mi Gapp despues de colocar certicado SSL a mi servidor de GLPI

![Imagen de WhatsApp 2023-11-02 a las 09 15 15_df2b87d3](https://github.com/ticgal/gapp/assets/51798064/53e81468-d230-434a-857a-633b50afc30f)

Me pueden orientar a ver de que se trata ?

**Comment by OscarBeiro** [comment]
Hi,
Typically your issue is related to a self-signed certificate or an SSL misconfiguration.
Please check: https://tic.gal/en/ssl-certificate-error-seems-like-is-an-error-with-glpi-server-ssl-certificate-you-are-trying-to-access/
Regards,
