### ISSUE TITLE
Task rendering

### ISSUE THREAD

**Issue by gelsoniezzi** [ticgal/gapp#66]
Problema na renderização das tarefas.

![WhatsApp Image 2023-12-11 at 14 59 31](https://github.com/ticgal/gapp/assets/6624897/099ff390-67d6-44af-9d55-51363321dec9)

**Comment by OscarBeiro** [comment]
Hi, 

We have confirmed your issue. We will release a new beta after the holidays.
As a workaround, you can leave the beta and go with stable.

Thanks for the report.
Regards,

**Comment by PedroTicGal** [comment]
Hi @gelsoniezzi, 

Thank you very much for your feedback above all. 

We've just released a new version addressing the issue you reported in this matter. The new version corresponds to 2.5.1 (000420) and is available on the beta channel on Google Play. 

Thank you so much. 

Have a wonderful holiday season.
