### ISSUE TITLE
ERROR_SESSION_TOKEN_MISSING when trying to log in

### ISSUE THREAD

**Issue by cmmata** [ticgal/gapp#68]
Hello!

I'm trying to get Gapp working, but after a bit of troubleshooting configuring GLPI Rest API, I'm running into this ERROR_SESSION_TOKEN_MISSING error. I have checked #44, but the user gets this working without more explanation. I also checked the tutorial link there, but it's another error that I already solved.

![Screenshot_20240223-185412](https://github.com/ticgal/gapp/assets/4223148/367311a3-5f52-4ac4-9308-b171bfd5929d)

I'm using GLPI 10.0.12 installed from tar (yeah, old school, I know...) and Gapp 2.5.1 from play store. Gapp essentials if needed, is on version 2.2.0.

Is there anything I can check or try to debug this? The API client history only shows Endpoint called from XXX IP.

**Comment by cmmata** [comment]
I'm sorry, it's solved now. I thought I needed to insert the full rest API path (server/restphp) like in the reminders browser plugin. But today I tried with only the domain, and I was able to log in. We can close this.

Anyway, thanks for the effort maintaining the app! Looks like very useful

**Comment by OscarBeiro** [comment]
Thanks for the feedback!
