### ISSUE TITLE
[Feature]Push notifications

### ISSUE THREAD

**Issue by reinethernal** [ticgal/gapp#8]
**Is your feature request related to a problem? Please describe.**
That would be great to add a push-notifications to the app. 
**Describe the solution you'd like**
When a new ticket or followup created a push-notification is received.

**Comment by OscarBeiro** [comment]
Hi,
We are working on this feature. Unfortunately, we don't think this could be easily achieved for the free app since it will involve an additional messaging service.
Regards,

**Comment by reinethernal** [comment]
Maybe this could help?
https://www.truepush.com/blog/index.php/api-integrationhttp-website/

**Comment by OscarBeiro** [comment]
Hi @reinethernal,
They still use FCM and its not possible to set it up except for a custom app.
Regards,

**Comment by reinethernal** [comment]
Hello again. And what about gotify? Is it possible to add such feature:
- User set up gotify server on his own, 
- Creates api key
- Enters key and url of gotify server
- Starts receiving push notifications
