### ISSUE TITLE
[Feature] Wrong russian translation

### ISSUE THREAD

**Issue by secfilatov** [ticgal/gapp#9]
**Sponsor a feature**
...

**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
There are different first letter registry in the left menu of Russian Language App
мои заявки
Назначенные заявки
все заявки
В ожидании утверждения
о
And I think that the string "о" is not right might be "О программе"
Same problem on Login Screen Пользователь, пароль

**Describe alternatives you've considered**
Please correct Strings in Russian Language

**Additional context**

**Comment by OscarBeiro** [comment]
Hi @secfilatov,

Sorry about this.  We don't have enough Russian knowledge to release a translation. This has been translated by a contributor: https://tic.gal/en/gapp-kudos/

We are in the middle of changing how we will handle translations. When we have a new solution I will update this issue to let you know how to correct it if you wish.

Спасибо :)

**Comment by OscarBeiro** [comment]
Hi,
We have migrated from our previous translation platform to Weblate.
You can suggest translations now, even without registering, and can be accepted if they are voted by other translators.

https://hosted.weblate.org/projects/gapp/gapp-selfservice/ru/

Regards,
